### ISSUE TITLE
Again the problem of asking for a password I've never created

### ISSUE THREAD

**Issue by fabiobfava** [crypto-com/chain-desktop-wallet#1009]
Sorry for opening an new ticket. I've been trying all suggestions on the topic below without success.

https://github.com/crypto-com/chain-desktop-wallet/issues/803

If I clear and restore a new wallet, all my 330 CRO disappear. I've managed before to restore from a backup, but it's not working any longer. I really need help I don't want to lose all my CRO...

**Comment by fabiobfava** [comment]
I've just removed the App and created a new wallet on my Ledger, but it's completely empty once again. I'd need to discover how to restore my previous existing CRO wallet on the App, with my funds and my staked CRO there. For the moment I only have a completely empty wallet, empty staking... Please help me.

**Comment by crypto-matto** [comment]
Hi @fabiobfava, I'm sorry once again that you might've forgotten your password. 

You may proceed to our [Mnemonic Code Converter](https://crypto-org-chain.github.io/bip39-webtool/) to help looking for the correct Address Index you've once used. 

Steps: 
1. In field BIP39 Mnemonic, input the 24-word recovery phrase of your Ledger Device
![image](https://user-images.githubusercontent.com/74586409/156115458-c38a41e6-0a25-4384-b683-bed5d4d3ed76.png)

2. In field Coin, select "ETH - Ethereum" or "CRO - Crypto.org Chain"
![image](https://user-images.githubusercontent.com/74586409/156115440-5f8446c3-cc4c-4cea-a61f-1e5930d6b7ef.png)

3. In Derivation Path, choose the tab "BIP44" without altering any values
![image](https://user-images.githubusercontent.com/74586409/156115499-e1b2a922-fb0b-47de-933d-72c61034f54c.png)

4. A list of Derived Addresses based on your 24-word recovery phrase will be generated.
![image](https://user-images.githubusercontent.com/74586409/156115535-4070ecbe-b1b2-4023-8bae-80e0c40b715e.png)
![image](https://user-images.githubusercontent.com/74586409/156115547-c0f8de84-f506-48bd-96fc-11d412ae454b.png)

5. Locate your original Ledger Address from the list generated. Please also mark down the corresponding Path and locate your Address Index. 
From the above example list, if `0xe40DA9815A8437ECda0B74ac1A13Fa9728bA195d` is the address you're looking for, the corresponding Path is `m/44'/60'/0'/0/5`. The final digit `5` is the Address Index you have to input when creating a Ledger wallet on [Crypto.org](https://urldefense.com/v3/__http://Crypto.org__;!!Ifoxw8Usf-Ni!dd7iibdF3dHa6glZWAKpSVDeFMEUw-_eXDBIoqVAQfgO8itgnjnsmHFXmKFVsRIrfQshs9j1Ty5-s7gtGcULRw$) Chain Desktop Wallet (Beta). You shall look up to 100 Ledger's default maximum Address Index is only up to 100. (Except you turned on Expert mode)

**Comment by fabiobfava** [comment]
Hello crypto-matto,

First of all, I was never asked to create a password when I’ve created my CRO wallet, I didn’t forgot it just was never asked to create it in first place.

Second, should I completely remove the CRO Beta App before succeding that, right?

After completely removing it, then I start this long procedure?

Cheers!

___________________________________________

Fabio Fava - https://fabiofava.com - ***@***.***

**Comment by fabiobfava** [comment]
After removing the App and its preferences, I was able to follow up to the step 4. but I cannot understand what is stated on the step 5. I cannot understand what you mean with "Please also mark down the corresponding Path and locate your Address Index", I cannot fin those fields anywhere. I can find my wallet address but don't know what to do then.

What you mean with "mark down the corresponding Path and locate your Address Index"? I have:
Path | Address | Public Key | Private Key

What and where can I find that "Address Index? At Step 5 I got completely confused and don't know what to do.

I'll keep looking forward from you on more detailed instructions on how to recover my wallet, thanks!

**Comment by fabiobfava** [comment]
Hey there, I've managed to recover! Thank you big time! Cheers!
