### ISSUE TITLE
Can't Open crypto.com desktop wallet mac or PC both 6.9 and after. 6.8 works

### ISSUE THREAD

**Issue by Senterium** [crypto-com/chain-desktop-wallet#1020]
**Describe the bug**
Can't open desktop wallet. Throws error. 6.8 works for me on both mac and PC but 6.9 and 7.2 does not work on either PC or mac with same exact error

**Environment and Version (please complete the following information):**
 - OS: [e.g. Windows, Mac, Linux]
 - Version [e.g. v0.0.1]

**To Reproduce**

**Expected behavior**

**Screenshots**

![Capture](https://user-images.githubusercontent.com/74579995/158078022-ee68fc07-3a07-4c8b-8aec-46e736c949a0.JPG)

**Additional context**

**Comment by crypto-matto** [comment]
Hi @Senterium, 

We found that this error ever happened on Mac when the upgrade loading kicked in and reopen quickly. When close and reopen once again, the error will not appear again. 

Based on this, it may possibly be your upgrade download process is either not finished/got stuck/paused in unknown situations, and caused some missing files/permission setup unfinished. Next time wait till the download finishes completely, it probably can resolve the issue.

Meanwhile, if you download our latest release and reinstall, it should also resolve your issue.

**Comment by Senterium** [comment]
Actually both of these were from fresh installs of 6.9-7.2 after uninstalling the program while the issue persisted. Uninstalled and reinstalled each version a few times.

Fixed in 7.4 !!
