### ISSUE TITLE
Problem: Missing new regions to the sanction list

### ISSUE THREAD

**Issue by cdc-Hitesh** [crypto-com/chain-desktop-wallet#1024]
Slack: https://crypt0-hq-hk.slack.com/archives/C027XJJM8JY/p1647419607837509

New regions to be added: 
- `Donetsk` 
- `Luhansk`

**Comment by crypto-matto** [comment]
Cloudfare side has already been blocking these 2 regions. No actions required on our side. 
Likewise though, the app would support these 2 regions whenever Cloudfare unblocks.

**Comment by crypto-matto** [comment]
Cloudfare side has already been blocking these 2 regions. No actions required on our side. 
Likewise though, the app would support these 2 regions whenever Cloudfare unblocks.
