### ISSUE TITLE
Missing reward after redelegate

### ISSUE THREAD

**Issue by cruz3neo** [crypto-com/chain-desktop-wallet#1041]
I read that redelegate will auto claim the pending CRO rewards. However I redelegate recently, there were no rewards.

Tx Hash : BE7FB5AD8C470F5A7C8AAE19672F10092B4AC6F02AE47C33135782B626708B60

**Comment by crypto-matto** [comment]
Hi @cruz3neo. 
Sorry that the explorer isn't showing the `Auto Claimed Reward`, which could cause your confusion. 

From the raw data: https://crypto.org/explorer/api/v1/transactions/BE7FB5AD8C470F5A7C8AAE19672F10092B4AC6F02AE47C33135782B626708B60
```
"autoClaimedRewards":{"denom":"basecro","amount":"2428881986"}
```
You've already auto claimed 24.28881986 CRO rewards on your redelegation.
You shall be able to see this record & the corresponding reward amount in `Assets` => `CRO` => `Transactions` of Desktop Wallet as well.

**Comment by crypto-matto** [comment]
Hi @cruz3neo. 
Sorry that the explorer isn't showing the `Auto Claimed Reward`, which could cause your confusion. 

From the raw data: https://crypto.org/explorer/api/v1/transactions/BE7FB5AD8C470F5A7C8AAE19672F10092B4AC6F02AE47C33135782B626708B60
```
"autoClaimedRewards":{"denom":"basecro","amount":"2428881986"}
```
You've already auto claimed 24.28881986 CRO rewards on your redelegation.
You shall be able to see this record & the corresponding reward amount in `Assets` => `CRO` => `Transactions` of Desktop Wallet as well.

**Comment by cruz3neo** [comment]
Hi @crypto-matto,

Sorry i check, however it was not inside and the totally balance dun add up. 

![image](https://user-images.githubusercontent.com/102530402/160803459-0d9e63d0-e2c6-4d5f-9d0a-569b8b69dab8.png)
