### ISSUE TITLE
Password 

### ISSUE THREAD

**Issue by Mikec90** [crypto-com/chain-desktop-wallet#1069]
**Describe the bug**

 - OS: IOS 
 - Version: v0.0.11

1. Go to: Crypto.org
2. Click on: Login  and type in password.
3. Scroll down to: Login & Click on.

**Expected behavior**
Expected to redirect to Crypto.org Chain Home page.

**Screenshots**
N/A

**Additional context**
Will not proceed to next page and stuck on Login Page. Password is Correct and does not turn red. (Bug Report)

**Comment by crypto-matto** [comment]
Hi @Mikec90, not sure if you're referring to DeFi Wallet mobile app, but this is Desktop Wallet instead. You're able to reach their customer service in Main App.
