### ISSUE TITLE
Looks like the staking CLI wallet 1.7.4 balance oscillates between amounts. No access to wallet other than myself. Must be a bug with the wallet.

### ISSUE THREAD

**Issue by Senterium** [crypto-com/chain-desktop-wallet#1230]
<img width="472" alt="Screen Shot 2022-08-29 at 4 02 03 PM" src="https://user-images.githubusercontent.com/74579995/187316285-18b59b7d-645f-40bb-a444-257fc8f326da.png">

**Comment by Senterium** [comment]
<img width="306" alt="Screen Shot 2022-08-29 at 8 07 12 PM" src="https://user-images.githubusercontent.com/74579995/187340115-a9d46839-aed1-4210-97d9-520d6606b451.png">

**Comment by crypto-matto** [comment]
HI @Senterium, this is the repository of Crypto.com DeFi Desktop Wallet. I'm afraid this is unrelated to our wallet or any other products.
