### ISSUE TITLE
Issue: Consider to withdraw ATOM from compulsory assets in Ledger wallet

### ISSUE THREAD

**Issue by crypto-matto** [crypto-com/chain-desktop-wallet#1245]
## Background
In older generations of Ledger Nano S, 3 required apps (Crypto.org, Ethereum, Cosmos) has already occupied literally all spaces of the device. Any bigger size update in the future would result in the Desktop Wallet incompatible with old Ledger Nano S devices.
<img width="766" alt="螢幕截圖 2022-09-19 下午4 41 05" src="https://user-images.githubusercontent.com/74586409/190983242-6a22f3b2-8467-457f-858b-11bd67075434.png">

## Solution
Consider to withdraw the less-important ATOM from compulsory assets in Ledger wallet 

## Tasks
- Adjust several actions for Ledger Wallet
  - no. of static assets checking
  - remove Cosmos ATOM in migration flow 
- Add Cosmos ATOM flow in Asset page
  - Apply CRO address validation check prior to Cosmos ATOM address creation
- Handling when Cosmos ATOM is not added
  - Remove Cronos <-> Cosmos Hub Bridge Transfer
  - Remove ATOM fetching

**Comment by LDbigG** [comment]
> ## Background
> In older generations of Ledger Nano S, 3 required apps (Crypto.org, Ethereum, Cosmos) has already occupied literally all spaces of the device. Any bigger size update in the future would result in the Desktop Wallet incompatible with old Ledger Nano S devices. <img alt="螢幕截圖 2022-09-19 下午4 41 05" width="766" src="https://user-images.githubusercontent.com/74586409/190983242-6a22f3b2-8467-457f-858b-11bd67075434.png">
> 
> ## Solution
> Consider to withdraw the less-important ATOM from compulsory assets in Ledger wallet
> 
> ## Tasks
> * Adjust several actions for Ledger Wallet
>   
>   * no. of static assets checking
>   * remove Cosmos ATOM in migration flow
> * Add Cosmos ATOM flow in Asset page
>   
>   * Apply CRO address validation check prior to Cosmos ATOM address creation
> * Handling when Cosmos ATOM is not added
>   
>   * Remove Cronos <-> Cosmos Hub Bridge Transfer
>   * Remove ATOM fetching
