### ISSUE TITLE
Problem: missing support for hw wallet type in creating wallet

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-com/chain-desktop-wallet#198]
when creating wallet
can choose types

because wallet txhistory and other data are tightly coupled directly to UI.
it would be handled with recoil & neb-promises like now

no connecting, disconnecting ledger buttons are necessary.
automatically connected if current wallet is ledger wallet.

1. normal wallet
2. ledger wallet <- no mnemonics
3. trezor wallet <- no mnemonics
etc.

**Comment by eddycpc** [comment]
Was implemented
