### ISSUE TITLE
Problem : Optimize UX related to Ledger Support

### ISSUE THREAD

**Issue by crypto-matto** [crypto-com/chain-desktop-wallet#218]
1. Create Page
- `Want to create hardware wallet?` checkbox is unchecked after finishing `Custom Devnet` setting
-  Default wallet type is `Ledger` while `Want to create hardware wallet?` checkbox is checked. Vice Versa when unchecked.
- Currently, only `The derivation path might be incorrect` is shown for whatever errors. 
- Checkbox shouldn't be shown during the creation of the first wallet
- Before going ahead and try to create a hardware wallet, there should be a step where we show a dialog that will check for hardware wallet connection. 

So generally the flow might look like this :

- User specifies they want to create a hardware wallet. Ledger get sets as default

-  And then the wallet create button should become "Connect Ledger (or something)" 

- When clicked it should test if the hardware wallet is connected and ready to be used. This is where we can show errors like "Failed to connect to the specified hardware wallet" when there's no hardware wallet connection

- If there's a connected hardware wallet then we can jump to the usual creation flow.

2. Home Page
- In wallet selection, all wallets are under `Wallet List`. Should group the Ledger Wallets in `Ledger Wallet List`?
- Wallet data fetching seems unstable & might fail easily when switching between Ledger & Normal Wallets?

**Comment by eddycpc** [comment]
Was resolved
