### ISSUE TITLE
Problem: design enhancement for undelegate

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-com/chain-desktop-wallet#251]
![image](https://user-images.githubusercontent.com/51560997/108027077-ea066a80-706c-11eb-8235-cd16452770e8.png)

how about round-shaped box for `undelegate` ?

**Comment by eddycpc** [comment]
Good suggestion.
I think @crypto-matto will have a look at this soon when he's available.

**Comment by crypto-matto** [comment]
If you look at the original design, Design Team intend to just use colored text for all actions. 

<img width="715" alt="螢幕截圖 2021-02-23 下午12 37 36" src="https://user-images.githubusercontent.com/74586409/108802765-f9893480-75d3-11eb-8f64-f6c688a97e1d.png">
<img width="604" alt="螢幕截圖 2021-02-23 下午12 37 58" src="https://user-images.githubusercontent.com/74586409/108802780-fc842500-75d3-11eb-9119-1d234fddd635.png">

**Comment by crypto-matto** [comment]
I think we may have a dedicated page to display all undelegation process. 
<img width="629" alt="unstake" src="https://user-images.githubusercontent.com/74586409/114127047-3616b280-992c-11eb-96f9-714f6c065a25.png">

**Comment by crypto-matto** [comment]
Currently we don't have any api returns the remaining days of un-delegate / re-delegate locking period. We may log every related transactions into our DB and count for remaining days.
