### ISSUE TITLE
Problem : Phase 2 UI improvements for ledger support

### ISSUE THREAD

**Issue by crypto-eddy** [crypto-com/chain-desktop-wallet#252]
- Possibly a ledger icon in the wallet home screen specifying to the user that they are using a ledger backed wallet.

- Show a UI pop-up when the user is asked to approve a transaction directly from the Ledger device.

**Comment by lezzokafka** [comment]
- For Delegating funds under staking operations, it shows "Top validators" with their addresses. 
We can consider also adding human readable ids such as the node id along with that.

**Comment by calvinaco** [comment]
Problem: Show error message when user tries to connect a Ledger wallet but Ledger cannot be connected

How to reproduce:
- Do not connect Ledger to the PC
- Create a new wallet with Ledger
- Click "Create"
- The popup to connect Ledger appears
- The popup disaappers

What can be improve/expected?
- Display an error message based on the error (App not open, not connected etc (if know))

**Comment by leejw51crypto** [comment]
i'll work on it
