### ISSUE TITLE
Problem : Floating point rounding issue

### ISSUE THREAD

**Issue by eddycpc** [crypto-com/chain-desktop-wallet#260]
I guess there will be problem in existing “send all” flow, I guess the root cause is the balance display issue somewhere.
steps to reproduce:
- precondition: accountA has balance = 5 tcro
- accountA send 5 tcro (withdraw all) to accountA.
- accountA should have 4.99995tcro. actual: showing 5.0000 in desktop wallet and explorer. reference
- accountA send 5 tcro(withdraw all) to accountA.
error show. onchain failure.reference
please take a look when you are free. (edited)

**Comment by crypto-matto** [comment]
May reference on how I handled this issue on token-migration-webtool
https://github.com/crypto-com/token-migration-webtool/pull/65

I used the library https://github.com/MikeMcl/bignumber.js/ suggested by @calvinaco
