### ISSUE TITLE
Problem: Missing delete wallet button

### ISSUE THREAD

**Issue by crypto-matto** [crypto-com/chain-desktop-wallet#267]
Based on internal QA feedback

**Comment by eddycpc** [comment]
@crypto-matto  I think we probably need to prioritize the  "deletion"  feature as it has been requested several times.

**Comment by crypto-matto** [comment]
I'd propose a wallet delete page / popup, followed by the below steps:
1. Left-bottom corner Wallet Selection
2. Delete Wallet button
3. Open delete wallet page / popup
4. Select a wallet to be delete from a dropdown (Can’t be the current selected wallet)
5. Ask for password confirmation
6. Delete the wallet

**Comment by eddycpc** [comment]
The backend functionality of the flow is already implemented. Now what we are waiting is the design and UI implementation of the frontend to fully close this ticket.
cc @crypto-matto
