### ISSUE TITLE
Problem: desktop wallet gets stuck when working with Ledger

### ISSUE THREAD

**Issue by tomtau** [crypto-com/chain-desktop-wallet#291]
@lezzokafka can extra more details from Discord on how to reproduce it:

>Sorry to bother you. In the end I managed to make a wallet address with my ledger. Let me explain, close the app, and then try directly, the app seems to be stuck, but it works in a few minutes (so you know in case other users have the same problem). So I have created 4 different wallet names in the app, and 2 of them have the same ledger address (this is what happens when you do tests). Ask, I’ll have a problem. There is no possibility in the desktop app to delete wallet names so as not to confuse me. Thanks

Discord discussion: https://discord.com/channels/783264383978569728/790404424433926155/818090504838971413

**Comment by tomtau** [comment]
regarding the "no delete button" and duplicate addresses ending up in the app -- it seems to be the same issue as discovered by the internal QA feedback: https://github.com/crypto-com/chain-desktop-wallet/issues/267

for the "stuck app", not sure if it's a known issue?

**Comment by tomtau** [comment]
is the "stuck app" resolved: https://github.com/crypto-com/chain-desktop-wallet/pull/290/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR13 in 0.0.24 -- @calvinaco ?

**Comment by leejw51crypto** [comment]
stuck is resolved by @calvinaco ,
(in creating wallet, it wait for user's approval)

**Comment by calvinaco** [comment]
> is the "stuck app" resolved: https://github.com/crypto-com/chain-desktop-wallet/pull/290/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR13 in 0.0.24 -- @calvinaco ?

Sorry for the late reply. Yes, if the users issues is got stuck during wallet creation with Ledger, then v0.0.24 should have fixed it. It is released here:
https://github.com/crypto-com/chain-desktop-wallet/releases/tag/v0.0.24
