### ISSUE TITLE
Problem: missing support of flutter

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-com/chain-desktop-wallet#292]
support flutter
to get fast speed in mobile

currently, electron speed is ok, but not fast as native, especially on mobile.

Ledger module can be added natively using ffi

**Comment by eddycpc** [comment]
Adding support for Flutter would mean literally rebuild everything in Flutter which is not really a high priority at least not for now

**Comment by leejw51crypto** [comment]
ok

**Comment by tomtau** [comment]
given the project title says "desktop", the potential mobile speed (if I understand the problem description) is probably not immediately relevant, so will close this for now
