### ISSUE TITLE
Problem: Ledger device is not recognised 

### ISSUE THREAD

**Issue by fgatin** [crypto-com/chain-desktop-wallet#293]
A Ledger device (Nano X) is often not detected, even though it is connected to the computer, a Macbook Pro 16 inch running macOS Big Sur 11.2.2 (20D80). 

<img width="384" alt="Screenshot 2021-03-08 at 09 33 56" src="https://user-images.githubusercontent.com/6486288/110300107-c9d82480-7ff6-11eb-80e0-b80f01c6fc3b.png">

I need to close the Desktop Wallet and open it again a couple of times for the Ledger to finally be detected.

**Comment by leejw51crypto** [comment]
I'll check @fgatin

**Comment by leejw51crypto** [comment]
started

**Comment by calvinaco** [comment]
Fixed in https://github.com/crypto-com/chain-desktop-wallet/releases/tag/v0.0.24
