### ISSUE TITLE
Problem : Present more details about validators : Their Names, Commission Rates, Domains and Icons

### ISSUE THREAD

**Issue by crypto-eddy** [crypto-com/chain-desktop-wallet#295]

**Comment by eddycpc** [comment]
<img width="1125" alt="Screen Shot 2021-03-12 at 1 45 57 PM" src="https://user-images.githubusercontent.com/73159521/110929705-4c375000-8339-11eb-9388-eb9104131c5c.png">


Currently, validators selection is looking like the screenshot above, but in the future, we might need to incorporate more details for selections like : Validator Names, Commission Rates, Domains, and Icons

This might require a separate screen or popup to incorporate all that information

**Comment by eddycpc** [comment]
@crypto-matto this can be added to the design requests to the product & design team
