### ISSUE TITLE
Problem: Potential precision lost when amount is too big or floating points

### ISSUE THREAD

**Issue by crypto-matto** [crypto-com/chain-desktop-wallet#308]
Issue mentioned in PR #304

**Comment by calvinaco** [comment]
Is this issued resolved already? @crypto-matto

**Comment by eddycpc** [comment]
This issue was created when we were working on input maximum values conversions, I remember for all those forms inputs it has now been moved to string mode and use BigNumber for validation

So this can be fixed now
