### ISSUE TITLE
Problem: Ledger does not accept custom derivation path

### ISSUE THREAD

**Issue by calvinaco** [crypto-com/chain-desktop-wallet#309]
If one use the Devnet with custom derivation path, the address derived is still the default derivation path.

**Comment by leejw51crypto** [comment]
started

**Comment by leejw51crypto** [comment]
full path config is not allowed with the ledger,
because, it should be bip44 , 394 , to interact  with cro inside the ledger

it will be adding "index" in creating ledger wallet

**Comment by linfeng-crypto** [comment]
yes, 394 is hard coded in ledger app

**Comment by Nawaz-Malik143** [comment]
#304

**Comment by Nawaz-Malik143** [comment]
#303

**Comment by Nawaz-Malik143** [comment]
#307

**Comment by Nawaz-Malik143** [comment]
#308

**Comment by Nawaz-Malik143** [comment]
#310

**Comment by Nawaz-Malik143** [comment]
#310

**Comment by Nawaz-Malik143** [comment]
#310

**Comment by Nawaz-Malik143** [comment]
Duplicate of #
