### ISSUE TITLE
Problem: Top Validators listed in Staking are not the top validators

### ISSUE THREAD

**Issue by samueltayishere** [crypto-com/chain-desktop-wallet#311]
In staking tab, Delegate Funds page, the drop down list for Validator address shows 'Top Validators' but they aren't the top. Currently based on testnet I am seeing validators in Ranks 8, 15, 18, 41, 50, 54

![image](https://user-images.githubusercontent.com/2001818/112282009-a503d280-8cc1-11eb-8375-1a06b9dd88fb.png)

https://github.com/crypto-com/chain-desktop-wallet/blob/83850e7ce1bd825b4398d16ffd6806b9e0b9a85f/src/service/rpc/NodeRpcService.ts#L158

I believe the problem is because the function is not sorting before slicing. This results in top validators not being the top.

**Comment by eddycpc** [comment]
Definitely was not filtering on shares level, will be fixing this asap :🙏
