### ISSUE TITLE
Problem: Missing support for storing more wallets

### ISSUE THREAD

**Issue by crypto-matto** [crypto-com/chain-desktop-wallet#326]
We only support up to 10 wallets at the moment.

To support up to 100 or even 200 wallets, we need a better illustration. For example, we may have a separate wallet list page with pagination, displaying fields like: `Name`, `Address`, `Network`, `Balance`, etc of each wallet. Of course, users are able to switch between wallets as well. 

The existing bottom-left corner wallet selection may just show up to 10 recently opened wallets.

**Comment by eddycpc** [comment]
Looking at the code it seems to only allow 9 wallets, there might be a slight off by one bug
