### ISSUE TITLE
Cannot Connect to Ledger Device

### ISSUE THREAD

**Issue by auroralabs** [crypto-com/chain-desktop-wallet#333]
Ledger X has been fully updated and connects to Ledger Live ok. Installed the Crypto.com Wallet on OSX 10.11.6 no problem however when i select Ledger and connect after unlocking the device all i get is a popup with no error message

Cannot detect any Ledger device
Please connect with your Ledger device

**Comment by eddycpc** [comment]
@leejw51crypto can you look into this?

**Comment by aquilafedele** [comment]
I was able to connect and create a wallet with my Ledger Nano X today. I'm using MacOS 11.2.3.
Sometimes it's hard to have the wallet see the Ledger, but restarting the app and disconnecting/reconnecting the Ledger USB cable works every time.

**Comment by piotrholda** [comment]
Restarting/reconnecting does not help on Windows 10.

**Comment by ctml91** [comment]
Run the ledger wallet as administrator in Windows.

**Comment by arrabyte** [comment]
Same problem on Linux (Ubuntu 18.04) Ledger is not detected.

**Comment by arrabyte** [comment]
> Same problem on Linux (Ubuntu 18.04) Ledger is not detected.

Resolved.
Running the wallet by command line the log shows:

> enableWallet error Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found

To provides required dependencies install gcc-9 and g++-9.
