### ISSUE TITLE
Unable to Withdraw Awards

### ISSUE THREAD

**Issue by Chinkey1234** [crypto-com/chain-desktop-wallet#342]
Device: Ledger Nano X
App: Crypto.com Chain v2.16.3 (Ledger Install) (also tried Crypto.org Chain v2.16.5)
Error: The reward withdrawal transaction failed. Please try again later
Desktop Wallet: SAMPLE WALLET v0.1.1

When I try to withdraw rewards, I get to the point where I can view the transaction on the device and sign the transaction on the device but directly after signing the transaction, I get the following error: The reward withdrawal transaction failed. Please try again later

**Comment by calvinlauyh** [comment]
Hi @Chinkey1234 , is your account a vesting account? i.e. are you a reward receiver from Crossfire?

**Comment by Chinkey1234** [comment]
Hi - I believe my account is just a regular account. I receive CRO awards
from delegating my CRO coins to a validator.

**Comment by eddycpc** [comment]
This is probably fixed in this PR https://github.com/crypto-com/chain-desktop-wallet/pull/348

Related to custom address index on Ledger wallet type creations

**Comment by CeruleanAtMonaco** [comment]
> Device: Ledger Nano X
> App: Crypto.com Chain v2.16.3 (Ledger Install) (also tried Crypto.org Chain v2.16.5)
> Error: The reward withdrawal transaction failed. Please try again later
> Desktop Wallet: SAMPLE WALLET v0.1.1
> 
> When I try to withdraw rewards, I get to the point where I can view the transaction on the device and sign the transaction on the device but directly after signing the transaction, I get the following error: The reward withdrawal transaction failed. Please try again later

hi, @Chinkey1234 Your account needs to have some small balance to fund the fee, that is the usual reason it fails, please check if that's the case for you.

**Comment by Chinkey1234** [comment]
Hi - That was the issue. I was unaware that staking your entire balance and then try to withdraw rewards would cause the error message.
Perhaps some form of notification regarding that before committing to staking would be beneficial!

Thank for the quick response!
