### ISSUE TITLE
Problem: Transaction should display more decimal places

### ISSUE THREAD

**Issue by calvinlauyh** [crypto-com/chain-desktop-wallet#344]
Tried to send transaction with 1basecro and all will display as 0.0000 CRO
![image](https://user-images.githubusercontent.com/38898718/112714030-4c2b7880-8f13-11eb-9e85-f64213762b81.png)

**Comment by crypto-matto** [comment]
@eddycpc Should we display all tx numbers from `toFixed(4)` to `toFixed(8)` in `scaledAmount()` => `getUINormalScaleAmount()` ?

```
/// Get normal scale amount but fixed to 8 decimals
export function getUINormalScaleAmount(amount: string, decimals: number): string {
  const exp = Big(10).pow(decimals);
  return Big(amount)
    .div(exp)
    .toFixed(8);
}
```

Or we only show 8 decimal full scale in Tx Table columns?

**Comment by eddycpc** [comment]
> Or we only show 8 decimal full scale in Tx Table columns?

Yeah kind of

**Comment by eddycpc** [comment]
Being fixed now
