### ISSUE TITLE
Problem: missing display for tx failures

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-com/chain-desktop-wallet#349]
<img width="414" alt="image" src="https://user-images.githubusercontent.com/51560997/112717986-0f6b7b80-8f2b-11eb-9418-46ea59974f5e.png">

for example)
redelegation failure is quite common
```
Tx Failed
failed to execute message; message index: 0: redelegation to this validator already in progress; first redelegation to this validator must complete before next redelegation
```

display the cause of tx failures.

and for other common types,
incorrect sequence number

i suggest broadcastResponse contents is displayed to the user.
```
 const broadcastResponse = await this.client.broadcastTx(signedBytes);
      // eslint-disable-next-line no-console
      console.log(`tx failure= ${JSON.stringify(broadcastResponse)}`);
      if (isBroadcastTxFailure(broadcastResponse)) {
        // noinspection ExceptionCaughtLocallyJS
        throw new TypeError(`Transaction failed: ${JSON.stringify(broadcastResponse)}`);
      }
```

**Comment by leejw51crypto** [comment]
can display this error message

NodeRpcService.ts)
public async broadcastTransaction(signedTxHex: string): Promise {
... throw new TypeError(Transaction failed: ${JSON.stringify(broadcastResponse)});
...

**Comment by CeruleanAtMonaco** [comment]
> <img alt="image" width="414" src="https://user-images.githubusercontent.com/51560997/112717986-0f6b7b80-8f2b-11eb-9418-46ea59974f5e.png">
> 
> for example)
> redelegation failure is quite common
> 
> ```
> Tx Failed
> failed to execute message; message index: 0: redelegation to this validator already in progress; first redelegation to this validator must complete before next redelegation
> ```
> 
> display the cause of tx failures.
> 
> and for other common types,
> incorrect sequence number
> 
> i suggest broadcastResponse contents is displayed to the user.
> 
> ```
>  const broadcastResponse = await this.client.broadcastTx(signedBytes);
>       // eslint-disable-next-line no-console
>       console.log(`tx failure= ${JSON.stringify(broadcastResponse)}`);
>       if (isBroadcastTxFailure(broadcastResponse)) {
>         // noinspection ExceptionCaughtLocallyJS
>         throw new TypeError(`Transaction failed: ${JSON.stringify(broadcastResponse)}`);
>       }
> ```

I upvote for this issue to get fixed 😸

**Comment by calvinaco** [comment]
I also upvote this issue. For better display consider to extract the error code (if any) and error message instead of stringily it.

**Comment by crypto-matto** [comment]
Handling in #355
