### ISSUE TITLE
Step 2.4 from tutorial (ledger wallet) issue

### ISSUE THREAD

**Issue by Chemuto87** [crypto-com/chain-desktop-wallet#371]
When i try to add my wallet on ledger device as tutorial explain (https://crypto.org/docs/wallets/ledger_desktop_wallet.html#install-the-crypto-org-chain-desktop-wallet-app-for-ledger-and-create-the-wallet)

It request me about Address Index, i dont know what it is.

Could you help me please?

Thanks.
Best Regards.

**Comment by eddycpc** [comment]
Sure we can help.

The index selection on the Ledger wallet is for you to decide which address you want to use in the wallet. By default, you can just use 0 which will be just fine as the default wallet address.

I think our address we might just need to update the guides to explain more the idea behind index selection

**Comment by Chemuto87** [comment]
I'm trying but got this error:

![image](https://user-images.githubusercontent.com/81641143/113107672-7d9e8f80-9204-11eb-948f-b68ea5aacbab.png)

**Comment by Chemuto87** [comment]
Hi.

Thanks for all. Now is working. I follow the steps but it didnt work until i enabled "expert mode" on Crypto.org Chain App.

Thanks 
Best Regards.
