### ISSUE TITLE
v0.1.2 chain-desktop-wallet-0.1.2-x86_64.AppImage sha512 value

### ISSUE THREAD

**Issue by flenzi** [crypto-com/chain-desktop-wallet#380]
I'm having a different sha512 value than the one mentioned in the releases page https://github.com/crypto-com/chain-desktop-wallet/releases.

Expected:
```  
 sha512: WtocF2XHXMNeYEtg8FHpoN8neog2jMkeaplYtX5ACFQlcc1kFy49OtYtJO1Ipo9jdvALTQxSMsvDOmHE46FKdQ==
```
Actual:
```
$ sha512sum chain-desktop-wallet-0.1.2-x86_64.AppImage
5ada1c1765c75cc35e604b60f051e9a0df277a88368cc91e6a9958b57e4008542571cd64172e3d3ad62d24ed48a68f6376f00b4d0c5232cbc33a61c4e3a14a75 *chain-desktop-wallet-0.1.2-x86_64.AppImage
```

**Comment by eddywm** [comment]
Duplicate of https://github.com/crypto-com/chain-desktop-wallet/issues/370

You are using hex encoding while we present hashes in base64

If you convert the hex value `5ada1c1765c75cc35e604b60f051e9a0df277a88368cc91e6a9958b57e4008542571cd64172e3d3ad62d24ed48a68f6376f00b4d0c5232cbc33a61c4e3a14a75` to base64 you will that they actually match

https://base64.guru/converter/encode/hex

Maybe I should update the info in the release docs

**Comment by flenzi** [comment]
My bad, thanks

**Comment by eddycpc** [comment]
Duplicate of #370

You are using hex encoding while we present hashes in base64

If you convert the hex value 5ada1c1765c75cc35e604b60f051e9a0df277a88368cc91e6a9958b57e4008542571cd64172e3d3ad62d24ed48a68f6376f00b4d0c5232cbc33a61c4e3a14a75 to base64 you will that they actually match

https://base64.guru/converter/encode/hex

Maybe I should update the info in the release docs

**Comment by eddycpc** [comment]
> My bad, thanks

No worries, I think it was up to us to clarify that the checksums were in Base64

I have now updated and it's now clear with an added warning
