### ISSUE TITLE
Password reset

### ISSUE THREAD

**Issue by leob42** [crypto-com/chain-desktop-wallet#391]
there doesnt seem to be anyway to rest password? after speaking to someone on reddit apparently there should be a settings icon or drop down menu. I dont have this on my windows desktop?

**Comment by crypto-matto** [comment]
The settings icon might be missing from older releases. Please upgrade to latest release [here](https://github.com/crypto-com/chain-desktop-wallet/releases/tag/v0.1.4). 

You are able to reset your password (but also remove all your wallets) in `Settings` => `Clear Storage`. 
Please ensure that you have backed up your wallets' mnemonic phrase, or you will lose access to all your wallets. 
<img width="1275" alt="螢幕截圖 2021-04-03 下午11 12 28" src="https://user-images.githubusercontent.com/74586409/113482627-13bb0a00-94d2-11eb-85fe-f39a7ab439d2.png">
