### ISSUE TITLE
Withdraw rewards with ledger sign fail

### ISSUE THREAD

**Issue by satvbyte** [crypto-com/chain-desktop-wallet#392]
When signing the transaction for the withdrawal of the staking rewards with the ledger, the error "sign fail" is encountered.

<img width="1392" alt="Schermata 2021-04-02 alle 14 20 43" src="https://user-images.githubusercontent.com/47153306/113415167-f0536a80-93be-11eb-8b4f-5b31cc927c23.png">

**Comment by eddycpc** [comment]
This is a sort of a weird issue, shouldn't happen.

@leejw51crypto you can have a look into this if we are using the correct key index on signing rewards withdrawals inside the LedgerSigner

**Comment by Chemuto87** [comment]
"same" error when i try to delegate funds:
![image](https://user-images.githubusercontent.com/81641143/113485565-77cbd700-94ae-11eb-8c55-906bb7be6916.png)

**Comment by nschwermann** [comment]
Following this issue getting same error trying to delegate and an auth error trying to send

**Comment by leejw51crypto** [comment]
by some reason ledger is not detected
1. is ledger live, active, please close ledger live
2. detach, attach ledger, and run cro app of ledger again
3. for windows, run deskchain wallet with admin authority

**Comment by nschwermann** [comment]
thanks @leejw51crypto 
I am on OSX I have followed your steps of kill ledger live, reconnect and reopen crypto.org app on leger. And I still get the 'getPubKey fail' message when I try to delegate.

When I try to send a cro I get - "Bad status on response- 429"

Let me know if you would like me to somehow collect logs or something I am building client from scratch and can enable flag or other small changes.

**Comment by piotrholda** [comment]
I have the same issue during reward withdrawal on version 0.2.0. Error popup says:
An error happened!
The reward withdrawal transaction failed. Please try again later.
- sign fail
- Error
- Ledger assertion failed
- incorrect signature length 63

Voting was working on the same version previously.
I tried to restart the wallet and reconnect Ledger alredy.

**Comment by hendrikobo** [comment]
I have the same issue

If I try to sign with Ledger with/without expert mode to delegate or withdraw rewards there is all time an error with signature length:

The reward withdrawal transaction failed. Please try again later.

sign fail
Error
Ledger assertion failed
incorrect signature length 63
Windows10
Since Crypto.org wallet version 0.1.6

reinstalled ledger app& wallet , reinstalled last version , tried with/without expert mode , cleared cache but all time this error

**Comment by Harrk** [comment]
Issue occurred for me when attempting to delate 88 CRO to a validator. (Whilst holding 88.6875 CRO)

Same error as above:
```
sign fail
Error
Ledger assertion failed
incorrect signature length 63
```

Wallet versiion: v0.2.1
OS: Windows 10 (Version: 20H2, Build: 19042.985)
Ledger Fireware: 1.2.4-5
Ledger Crypto.org version: 2.16.5

Tried restarting app and running as admin, same issue. However when attempting to delegate a lower amount of CRO (87) it worked. I would suggest others with a similar issue try using a lower amount of CRO.

**Comment by Spindler360** [comment]
I've the same error since today. I haven't used the wallet since a week ago. Now it runs this error
sorry for doublepost. Can someone merge it?https://github.com/crypto-com/chain-desktop-wallet/issues/502

**Comment by sebastia36** [comment]
> I have the same issue during reward withdrawal on version 0.2.0. Error popup says:
> An error happened!
> The reward withdrawal transaction failed. Please try again later.
> 
> * sign fail
> * Error
> * Ledger assertion failed
> * incorrect signature length 63
> 
> Voting was working on the same version previously.
> I tried to restart the wallet and reconnect Ledger alredy.

I have this exact same error aswell, tried all of the above and nothing worked so far, please would appreciate if someone could have a look into it! Thanks!!
