### ISSUE TITLE
Problem: Error [big.js] Invalid number when loading the home page

### ISSUE THREAD

**Issue by calvinaco** [crypto-com/chain-desktop-wallet#393]
## How to reproduce?

- Clear the wallet storage
- Initialize the wallet with password and create a wallet
- Errors displayed when router to the home page

![image](https://user-images.githubusercontent.com/38898718/113430217-5a463100-940c-11eb-9bc6-c8d8bc1591da.png)

**Comment by eddycpc** [comment]
Working on this
