### ISSUE TITLE
[Feature request] Staking Rewards screen should show the Reward Amount in fiat

### ISSUE THREAD

**Issue by Techboy** [crypto-com/chain-desktop-wallet#396]
**Feature request**.

It would be useful if the Staking Rewards screen showed the total Reward Amount in fiat.

This could be displayed in a section at the top of the screen, like how Total Balance is listed in the Home screen.

**Comment by eddycpc** [comment]
This is a fair request, @crypto-matto can look into this

**Comment by crypto-matto** [comment]
Feature developed in #401
