### ISSUE TITLE
[Feature request] Preferred fiat currencies

### ISSUE THREAD

**Issue by Techboy** [crypto-com/chain-desktop-wallet#404]
**Feature request.**

Currently the only fiat currency shown is USD. It would be good to allow users to set them to their preferred fiat currencies (e.g. AUD, CAD, EUR, GBP, USD, SGD, etc.).

**Comment by eddycpc** [comment]
This is something we will definitely be supporting in the coming days/weeks

**Comment by crypto-matto** [comment]
The feature has developed & is under QA process. Shall be able to deliver in the next release.

**Comment by Techboy** [comment]
It's now implemented, thanks 👍
