### ISSUE TITLE
cant load/view validators 0.1.4 at certain wallet load up

### ISSUE THREAD

**Issue by subimpact** [crypto-com/chain-desktop-wallet#405]
![image](https://user-images.githubusercontent.com/15685593/113541750-71a43a80-9615-11eb-9a3a-5c20f81b4026.png)
seems like the list has intermittent on displaying  on 0.1.4

**Comment by eddycpc** [comment]
@subimpact 

You can try to go back to the home screen and click on the sync icon 🔄  and wait for the wallet to sync

After successfully syncing you should see a new fresh list of validators

**Comment by eddycpc** [comment]
This should be resolved by now
