### ISSUE TITLE
Documentation: How to restore a Ledger wallet?

### ISSUE THREAD

**Issue by dhinterlechner** [crypto-com/chain-desktop-wallet#406]
Even after carefully reading the documentation https://crypto.org/docs/wallets/ledger_desktop_wallet.html I did not found any hints on how to restore a Ledger wallet on the desktop client, where it asks me every time the memonic...
thanks

**Comment by eddycpc** [comment]
To restore a Ledger-based wallet, you can just go ahead and create a new one, make sure to use the proper index that you previously used.
