### ISSUE TITLE
App (v0.1.5) freezes after adding a Ledger wallet

### ISSUE THREAD

**Issue by Techboy** [crypto-com/chain-desktop-wallet#434]
**Describe the bug**
After setting up a wallet for Ledger Nano X, the application freezes and I can't click on anything.

**Environment and Version (please complete the following information):**
 - OS: Windows 10
 - Version App version 0.1.5

**To Reproduce**
1. Follow the guide https://crypto.org/docs/wallets/ledger_desktop_wallet.html#install-the-crypto-org-chain-desktop-wallet-app-for-ledger-and-create-the-wallet up to step 3.1
2. I can see the receive address in the app and in my Ledger Nano X
3. The app is then frozen and I can't click on anything

**Expected behavior**
The app should allow me to copy the address and navigate around the rest of the app.

**Screenshots**
The standard Receive screen with the address. No errors are shown.

**Additional context**
I already have a software wallet set up. This is a second wallet, for my Ledger Nano X.

The app is using 0% CPU, 72MB RAM.

**Comment by Techboy** [comment]
BTW, I restarted the app and it's working okay - I can see the same wallet address and can navigate around.

**Comment by eddycpc** [comment]
Hey @Techboy we are aware of some Ledger disconnections happening sometimes and we are fixing more and more of those issues.

We will be releasing soon v0.1.6 with some noticeable improvements on that side, when it's available you will let us know how it goes.

**Comment by Techboy** [comment]
I haven't had any Ledger related issues with v0.1.6 or v0.2.0.
