### ISSUE TITLE
Problem: Vesting account transaction operation is not supported

### ISSUE THREAD

**Issue by calvinaco** [crypto-com/chain-desktop-wallet#437]
**Describe the bug**
If I try to execute any transaction on a vesting account (any types) in the wallet, the wallet will return an error of "Unsupported Type"

**Environment and Version (please complete the following information):**
 - OS: [e.g. Windows, Mac, Linux]: Mac (but should not matter)
 - Version [e.g. v0.0.1]: Latest develop branch

**To Reproduce**
1. Create/Restore a vesting account
2. Open "Send" tab and try to send some funds from the account to any other account
3. Confirm the transaction
4. Error occurs

**Expected behavior**
I should be able to move the funds and stake my vesting funds without any error

**Screenshots**

![image](https://user-images.githubusercontent.com/38898718/114694434-1aa51080-9d4d-11eb-995e-4cbf9519dd0f.png)

```
Error occurred while transfer Error: Unsupported type: '/cosmos.vesting.v1beta1.DelayedVestingAccount'
    at Object.account (auth.ts:38)
    at async StargateClient.getAccount (stargateclient.ts:153)
    at async NodeRpcService.fetchAccountNumber (NodeRpcService.ts:72)
    at async WalletService.prepareTransaction (WalletService.ts:313)
    at async WalletService.sendDelegateTransaction (WalletService.ts:106)
    at async onConfirmDelegation (staking.tsx:159)
```

**Additional context**

**Comment by calvinaco** [comment]
I am do some quick study and this error originates from the cosmjs client, after digging into the code it appears to come from
https://github.com/cosmos/cosmjs/blob/8e4813405c182d3d0f5625a88f8a3ea9d09347cd/packages/stargate/src/queries/auth.ts#L27

A new version has been released with support of more types:
https://github.com/cosmos/cosmjs/commit/8804e0ccb27482237b5ccbc20aa3f224fe595206#diff-422398c01126667af0a2fc422f5c8e588342381f015659c5530ec46d662cb649

So ideally all we need is to upgrade to later version of cosmjs.

**Comment by HankFit247** [comment]
This issue should auto resolve itself on 3/22/2022 or 3/23/2022 when the one year vesture expires.

**Comment by crypto-matto** [comment]
The vesting account transactions are supported since v0.6.4
- #925
