### ISSUE TITLE
Documentation: staking rewards compound?

### ISSUE THREAD

**Issue by GiuseppeDM98** [crypto-com/chain-desktop-wallet#445]
After searching both on the web in general and on Reddit, I have not found any documentation regarding the staking rewards compound,.
The rewards I get from a validator are directly redelegated to the validator itself (so they go to compound) or to do this I have to withdraw them and then redelegate?

Edit: Thanks in advance and I apologize if this is not the place to ask for these things!

**Comment by crypto-matto** [comment]
Hi @GiuseppeDM98 ,

> The rewards I get from a validator are directly redelegated to the validator itself (so they go to compound) or to do this I have to withdraw them and then redelegate?

Yes 2 actions are required. You'll have to withdraw reward & delegate the validator again.
