### ISSUE TITLE
After undelegate, stake balance still showing up in UI as staked so unsure if still staked or being undelegated

### ISSUE THREAD

**Issue by adiptee** [crypto-com/chain-desktop-wallet#455]
Hi,

After undelegate, stake balance still showing up in UI as Staked so unsure if still staked or being undelegated.

I undelegated Stake and showed as success. However, in the app UI, it's still showing my staked balance as the same. When I look at my wallet address, it shows as Undelegate was Success though. I tried to Undelege in the app again, but throws error as "no delegation for (address, validator) tuple", so I'm assuming it's saying my Undelegate call was indeed successful, but something is out of sync with the app UI? I closed the app and restarted and still shows balance as Staked.

Still shows on the Home --> Delegations tab / Staked Balance (incorrect).
No longer showing stake on the Staking tab (correct).

Thanks for your help.

**Comment by eddycpc** [comment]
Hey @adiptee 

The reason it's still showing is because undelegation takes around 28 days to fully complete, so in the meantime the balance is still kinda locked until the end of that period.

**Comment by adiptee** [comment]
Hi @eddycpc,

Thanks for the clarification.

My only concern here is that I did two Unstakes, and only one is still showing on the Staked Balance and one disappeared. So, it would make sense if both still showed or both disappeared.

**Comment by HankFit247** [comment]
Greater transparency would be great.

We don't need the noobs on FB filling the groups with questions.

Undelegate and countdown.  Similar to EARN in Crypto.com app.

**Comment by Techboy** [comment]
I agree, the app should show the state of the stake, as well as the date it will be undelegated.

I have just undelegated and the app doesn't show this - it still shows the 'Undelegate Stake' option, which is misleading. https://crypto.org/explorer/ confirms that the 'undelegate' action was executed.

**Comment by crypto-matto** [comment]
The enhancement was made since v0.5.1 
- #746
