### ISSUE TITLE
Show more than 4 numbers after the comma

### ISSUE THREAD

**Issue by BlackHitama** [crypto-com/chain-desktop-wallet#458]
I have one small comment. The wallet displays only 4 digits after the comma while the explorer and the DeFi wallet shows 8 digits. It would be nice if it was possible to add the 4 digits (in send)  to wipe an address for example.

**Comment by wildera** [comment]
I submitted a pull request (#460) to show all decimals only when necessary, hope it will help!

**Comment by BlackHitama** [comment]
Thank you! I will close this request then
