### ISSUE TITLE
Application doesn't ask for password on open

### ISSUE THREAD

**Issue by fabiobfava** [crypto-com/chain-desktop-wallet#459]
**Describe the bug**
The App (0.2.0 - MacOS) has asked for a password when I've frist opened, but never asked again that password to open the application.

**Environment and Version (please complete the following information):**
 - Mac OS 10.14.6 Mojave
 - Crypto.org Chain Desktop Wallet (Beta) for Mac 0.2.0
  
**To Reproduce**
Don't know how to reproduce. I've created a password to open the applicaiton on the first time I've run it, but the application opens without asking for my password.

**Expected behavior**
The application should ask for the password that has been created on application's first run.

**Screenshots**
No need, it just doesn't ask for the password on open.

**Additional context**
Couldn't say.

**Comment by crypto-matto** [comment]
Hi @fabiobfava The `App Password` is only used for encrypt & decrypt `Normal` type wallets. Guess you've created a `Ledger` type wallet with a Ledger Device, which doesn't require the `App Password` for any operations.

**Comment by fabiobfava** [comment]
Thank you,

On the other hand, the Crypto.com app doesn’t support Brazil, where I live.

I have funds parked on the Crypto.com app, that I would like to stake on my Ledger Wallet account, so it can grow in CRO. 

I would need some way to have my Crypto.app funds transferred to the Desktop Wallet App, so I can earn there as I’ma lready earning on the CROs I have there.

I’ll keep looking forward from you about some way to do that tranfer.

Thank you very much and best regards,

___________________________________________

Fabio Fava - https://fabiofava.com - ***@***.***

**Comment by 1mdc** [comment]
I have same problem. Cannot create wallet due to this error.
