### ISSUE TITLE
sha512 sum in base64? how?

### ISSUE THREAD

**Issue by github12101** [crypto-com/chain-desktop-wallet#463]
"When verifying the SHA512 checksum please do use the Base64 encoding instead of the default hex encoding to match the output we provide in Base64"

I use Linux. I don't know how to make a sha512 hash in base64. How we supposed to do that? I could not find it anywhere in instructions, I am sorry.

Why not use standard sha256 or sha512 hash, with GPG signed signature?

**Comment by eddycpc** [comment]
https://base64.guru/converter/encode/hex

You can use an online utility like the one above to convert a `hex` string to `base64`

If you want to use a local tool, then you can check the proposed solutions in the article below
https://unix.stackexchange.com/questions/205757/i-am-attempting-to-write-a-bash-script-to-convert-hex-to-base64

**Comment by eddycpc** [comment]
Related to this https://github.com/crypto-com/chain-desktop-wallet/issues/370

**Comment by github12101** [comment]
Why such complication? Why can't we just use "sha512sum filename" and that's it?

**Comment by eddycpc** [comment]
We use electron builder for the build process and that's how it's designed to checksum outputs

And base64 is definitely better than hex in that regard, thus the choice

**Comment by github12101** [comment]
"And base64 is definitely better than hex in that regard, thus the choice"

In what regard? It's indefinitely more difficult for users to check hash sums, so, what's better?
