### ISSUE TITLE
Not able to create wallet for the first time

### ISSUE THREAD

**Issue by 1mdc** [crypto-com/chain-desktop-wallet#479]
**Describe the bug**
I could not create wallet. It asks for password after 24 words but keeps saying incorrect password.

**Environment and Version (please complete the following information):**
Mac OS, 0.2.1 

**To Reproduce**
1. Open the app for the first time
2. Click on "Get Started"
3. Click on "Create wallet"
4. enter wallet name "test", click on "Create wallet"
5. popup success shows, click on "Next"
6. write 24 words, check "I understand...." and click on "i have...."
7. popup show "provide app password" and a textfield and a button "Encrypt wallet"
8. I enter a new password and click on "Encrypt wallet"
9. An error message show: "Password provided is incorrect". And a button Retry.
10. Click on retry go back to step 7

**Expected behavior**
It should allow set password and allow me to create wallet. I tried with many different password combinations but it did not help.

**Screenshots**
<img width="601" alt="Screenshot 2021-05-08 at 13 40 50" src="https://user-images.githubusercontent.com/5703525/117539532-04643a80-b003-11eb-9fe0-30ca64a58770.png">

**Additional context**

**Comment by eddycpc** [comment]
Hey, @1mdc if it's saying incorrect password all the time it means you are using a different password than the one you used initially when you created the wallet on the first screen.

You can still "Clear app storage" to start from afresh again.

**Comment by 1mdc** [comment]
Hi @eddycpc This is the first time I installed and used the app. I never set any password before. As I explained steps above, no step asks me to create a password.

I do not see any option to "clear app storage"

**Comment by 1mdc** [comment]
I solved the problem by myself. As mentioned above, the create password page was "skipped" due to it created a storage folder but one of the files corrupted, so it could not read storage correctly.

I deleted folder (in MAC) `/Users/[machine-user]/Library/Application Support/chain-desktop-wallet` and restarted the app, then it works. now.
