### ISSUE TITLE
[NFT-Support] Update default node to croeseid-3

### ISSUE THREAD

**Issue by crypto-matto** [crypto-com/chain-desktop-wallet#480]
Currently, only `testnet-croeseid-3` is installed with NFT module. So to support NFT, we will have to change the default nodeUrl settings for all testnet wallets. At the same time, we might need to propagate this change to all settings stored in wallet db. 

For our convenience, we could consider to change our default setting values from hard code in `chain-jslib` to be retrieved from: 
`https://github.com/crypto-org-chain/testnets/blob/main/testnet.json`
`https://github.com/crypto-org-chain/mainnet/blob/main/mainnet.json`
Also, prompt a popup to remind user to update latest default settings whenever the json is updated.

**Comment by eddycpc** [comment]
Fixed
