### ISSUE TITLE
[NFT-Support] Initial design implementation work

### ISSUE THREAD

**Issue by eddycpc** [crypto-com/chain-desktop-wallet#482]
Start implementing the new designs frames

**Comment by crypto-matto** [comment]
Current progress: 
<img width="1256" alt="螢幕截圖 2021-05-26 下午3 31 10" src="https://user-images.githubusercontent.com/74586409/119620328-72986200-be37-11eb-951b-160bb32ea761.png">

<img width="1268" alt="螢幕截圖 2021-05-26 下午3 31 00" src="https://user-images.githubusercontent.com/74586409/119620309-6dd3ae00-be37-11eb-92d2-2b3d9c9215f9.png">

**Comment by eddycpc** [comment]
Fixed on https://github.com/crypto-com/chain-desktop-wallet/pull/501
