### ISSUE TITLE
SEND/STAKING Error

### ISSUE THREAD

**Issue by Fokia84** [crypto-com/chain-desktop-wallet#497]
**Describe the bug**
When I try to send or to staking some CRO I've receive the error in attachment.
"The staking transaction failed. Please try again later.
- getPubKey all
- TransportError
- NoDevice"

**Environment and Version (please complete the following information):**
 - OS: Mac OS

**To Reproduce**

**Expected behavior**

**Screenshots**
![IMG_1309](https://user-images.githubusercontent.com/84899680/119788094-21897c00-bed2-11eb-9b75-d20ee6f51f01.jpg)

**Additional context**

**Comment by eddycpc** [comment]
Hey there, this is likely caused by ledger disconnects, did you try to disconnect and re-connect the Ledger device during the session and see how it goes ?

**Comment by Fokia84** [comment]
Hi Eddy,
there was a problem with my USB port. Fixed it and now work fine.

Thanks,
Giacomo

**Comment by eddycpc** [comment]
Awesome, glad to hear this was resolved on your side 🙏

**Comment by Fokia84** [comment]
Hi Eddy,
I would undelegate my stake but I’ve this message



What’s the problem? 
Where can I read full documentation?

Thanks in advance.

Giacomo
