### ISSUE TITLE
Reward withdrawal transaction failed. sign fail with Ledger (Nano X)

### ISSUE THREAD

**Issue by Spindler360** [crypto-com/chain-desktop-wallet#502]
**Describe the bug**
Error message when withdrawal the Staking Rewards

**Environment and Version (please complete the following information):**
 - OS: Windows 10 Pro (Version 10.0.19041 Build 19041)
 - Error on Wallet version: v0.2.2 and v0.2.1
 - Ledger Fireware: 1.3.0
 - Ledger Crypto.org version: 2.16.5

**To Reproduce**
1. Go to 'Staking'
2. Click on 'withdrawal '
3. Control and confirm on the Ledger Nano X

**Expected behavior**
- Root cause identification and troubleshooting

**Screenshots**
![image](https://user-images.githubusercontent.com/36817738/120366019-6f0d4b00-c30f-11eb-8c2f-d1c7f17a7c4c.png)

**Additional context**
The error happend sice today. Previously, the error did not occur in both versions for me.
I also tried to clear the storage and restore the wallet. Restore successful, error remains.🤷‍♂️

**Comment by Spindler360** [comment]
I also tried to clear the memory and restore the wallet. Restore successful, error remains.🤷‍♂️

**Comment by Spindler360** [comment]
Is there any news on this problem? I suspect it has to do with the latest rollout for ledger update (https://support.ledger.com/hc/en-us/articles/360014980580-Ledger-Nano-X-firmware-release-notes & https://donjon.ledger.com/lsb/016/). please check, comment and/or take a workaround. thanks

**Comment by sebastia36** [comment]
Same happened to me right now, also on a Mac OS, Catalina, 10.15.7.

I tried with the old version of the desktop wallet, and error ocurred, thought maybe there would be a new one which would fix. installed and nothing, same error as your picture. using a ledger nano X, and trying to pick up the rewards.  

Would appreciate if someone could check on that. so far nothing for me, will try again in a while but so far have checked the ledger for updates and nothing everything is as usual. 

Thanks!

**Comment by eddycpc** [comment]
@sebastia36 you mean you were being able to reproduce this same issue even on older versions. Because on our side it's working well on MacOS.

Can you check if you are able to connect to Ledger live app ?

**Comment by eddycpc** [comment]
@sebastia36 @Spindler360 
We are going to give more priority to these issues and hopefully, we shall fix these cases in the coming days.

Apologies for the temporary inconvenience.

**Comment by sebastia36** [comment]
> @sebastia36 @Spindler360
> We are going to give more priority to these issues and hopefully, we shall fix these cases in the coming days.
> 
> Apologies for the temporary inconvenience.

Yes, this error occurred by the time the 0.2.3 came out to me +-, until that time everything was going fine. I was on the 0.2.2 and when error appeared updated to the 0.2.3, but error persisted. Mac OS 10.15.7, and yes Ledger live works fine for what I know and tested. I did also delete and re-install everything even delete caches from those apps and error still there.

Thank you for giving high priority, 🙏🏼 Anything else you need I will try to answer soon.

**Comment by leejw51crypto** [comment]
working on it

**Comment by leejw51crypto** [comment]
hello, @Spindler360 
only withdrawal reward fails,
how about staking or transfer @Spindler360 ?

**Comment by sebastia36** [comment]
> hello, @Spindler360
> only withdrawal reward fails,
> how about staking or transfer @Spindler360 ?

I could not try as had no “funds” to stake or transfer really but as soon as I get home will be able to give it a try, it wont be until 18:30 though (Spanish time frame)

**Comment by leejw51crypto** [comment]
thanks, could you test via testnet ?

**Comment by eddycpc** [comment]
@sebastia36 https://github.com/crypto-com/chain-desktop-wallet/releases/tag/v0.2.4

We just released 0.2.4 can you please test it and let us know if the issue is fixed for your case. Thanks

**Comment by sebastia36** [comment]
> @sebastia36 https://github.com/crypto-com/chain-desktop-wallet/releases/tag/v0.2.4
> 
> We just released 0.2.4 can you please test it and let us know if the issue is fixed for your case. Thanks

Will do! Thank you! By the way, I did check yesterday and at least it’s posible to delegate, and when you delegate to the same validator you had your stake the rewards are collected so “that way” I could withdraw and compound the rewards in the meantime. But would be nice if this update fixes picking the rewards. Will check this afternoon (Spanish time frame) Thanks.

**Comment by sebastia36** [comment]
> @sebastia36 https://github.com/crypto-com/chain-desktop-wallet/releases/tag/v0.2.4
> 
> We just released 0.2.4 can you please test it and let us know if the issue is fixed for your case. Thanks

It worked perfectly to me already on the v0.2.4, thank you very much ☺️💪🏼👏🏼👏🏼
