### ISSUE TITLE
Problem: Creating a Ledger wallet stuck on provide app password screen

### ISSUE THREAD

**Issue by calvinaco** [crypto-com/chain-desktop-wallet#526]
**Describe the bug**
When trying to create a new wallet with Ledger, the creation process stuck at the screen of providing the app password forever.

**Environment and Version (please complete the following information):**
 - OS: Mac
 - Version: v0.2.3

**Screenshots**
![image (8)](https://user-images.githubusercontent.com/38898718/122755933-49e57a00-d2c8-11eb-90c1-070e1b42ff1e.png)

**Error log**

[Download Log File](https://github.com/crypto-com/chain-desktop-wallet/files/6686305/ledger-error.1.log)

![image (7)](https://user-images.githubusercontent.com/38898718/122755955-523db500-d2c8-11eb-86f4-5c4a097d10de.png)

**Comment by leejw51crypto** [comment]
it's authority issue,
should allow full-disk-access to the app, 
because ledger is represented as file path, as limited for access by default.

**Comment by audacity76** [comment]
For Windows, does this mean to run it as administrator? Because I'm getting the same error with latest Version (0.4.2).
