### ISSUE TITLE
Problem: missing detection of app changing inside ledger

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-com/chain-desktop-wallet#568]
when ledger app changes, detects it.
display the message in desktop wallet.

how about polling peoriodically to check ledger app inside ledger

**Comment by tomtau** [comment]
or just the other way round -- send a request to the device to switch to the correct app?

**Comment by arno01** [comment]
looks like duplicate of https://github.com/crypto-com/chain-desktop-wallet/issues/566 ?

**Comment by eddycpc** [comment]
> looks like duplicate of #566 ?

Yup they are closely related
