### ISSUE TITLE
Languages and Internationalization support on the app

### ISSUE THREAD

**Issue by crypto-3dd** [crypto-com/chain-desktop-wallet#575]
- [x] Add UI settings to select language
- [x] Integrate with a multi-language supported library
- [x] Add strings for internationalization and replace all static in-app strings
- [x] Pick a UI tool or even spreadsheets to hold translations and write a script to download the translation into the format to be used directly in the app.

**Comment by crypto-matto** [comment]
Google Spreadsheet for multi-language management:
https://docs.google.com/spreadsheets/d/1QTqPb97jr6zOD7krA4pAXHYx51CiSkJYq7m71OYcLok/edit#gid=0

App Script
https://script.google.com/home/projects/1X1WCMV0tbQsXvlkV70Kw_3gvF85zSxeqkUnTuDhul_EcdWG9ZU4_Z6ow/edit

**Comment by crypto-matto** [comment]
I'll make sure we would have at least 2 languages support first, then we may merge this PR & role out this feature.
