### ISSUE TITLE
Create a Cronos Rpc client service that interacts with the node for balance fetching, transaction broadcast, etc, ....

### ISSUE THREAD

**Issue by crypto-3dd** [crypto-com/chain-desktop-wallet#598]
Create a Cronos Rpc client that interacts with the node for balance fetching, transaction broadcast, transaction history fetching.

This RPC client service/class + interface should simplify the interactions between the wallet and the ethereum-like nodes.
Roles :

- [x] Fetching address balances.
- [x] Fetching address transaction history, the previous 20 transactions or more.
- [x] Broadcast transactions on-chain.
- [x] Should be flexible to work out of the box for all Ethereum-Like assets that would be supported later.

**Comment by cdc-Hitesh** [comment]
Do we want to:
- directly consume Web3 Provider in our Chain desktop (eg, infura/alchemy provider) or
- create a backend API service with ethereum related functionality (using nestjs etc)?

**Comment by crypto-3dd** [comment]
Just to clarify we will not have to create a new backend, I don't think it will be necessary.
As the ticket describes it, all we need is a simple class+interface that knows how to EVM broadcast transactions, fetch balances and load the latest transactions given an account address.

```javascript
interface EVMRpC {

function loadBalance(address: string) {}

function broadcastTransaction(signedTxHex: string) {}

function loadTransactions(address: string) {}

function fetchNonce(address: string) {}

//// etc

}
```

**Comment by cdc-Hitesh** [comment]
Noted. Thanks for the clarification.

**Comment by cdc-Hitesh** [comment]
Closed the issue
