### ISSUE TITLE
Undelegation Status Missing (and staking value disappeared)

### ISSUE THREAD

**Issue by Techboy** [crypto-com/chain-desktop-wallet#604]
**Describe the bug**
When undelegating 25,508.04660000 CRO it displayed an error message. So I tried again and got another message (I think the HTTP return code was different, but I didn't make a note of it).

My wallet now shows 'Staked Balance = 0 CRO' and the undelegation is not listed in the Transactions list.

I do see the undelegation listed here https://crypto.org/explorer/tx/9BAE983F91FEFFA8EF994D4C1C20DA54BC1C01C8D0DDF14A81242FDC85300130

**Environment and Version (please complete the following information):**
 - OS: Windows 11 Pro
 - Version	10.0.22000 Build 22000
 - Chain Desktop Wallet 0.3.8

**To Reproduce**
Open the Chan Desktop Wallet and view the 'Staked Balance' and Transactions fields.

**Expected behavior**
Should show the undelegated amount.

**Comment by crypto-matto** [comment]
Sorry for the confusion caused. We're revising the staking module, together with implementing a undelegation review section. You're able to see the status of your undelegations soon. Stay tuned!

**Comment by Techboy** [comment]
All working in v0.5.6 👍
