### ISSUE TITLE
Password in Windows Version 0.1.2 stop to work

### ISSUE THREAD

**Issue by DanielBoba** [crypto-com/chain-desktop-wallet#611]
After a few months i come back to the app to send CRO to a different wallet. The app open the wallet but the password doesn´t work for some reason.

is the only way to send my CRO at some different wallet because i can`t import the wallet. I don´t have the 12 keys. So, I know that this is not a bug but all my savings are there and is the only way to recover it. so wallet open but need sent. 

Any solution will be huge apreciated. all my savings are there.

Thanks for your time

**Comment by crypto-3dd** [comment]
The password can't suddenly stop working. You most likely forgot your password. In that case, you should use your recovery phrase.

If you forgot your password and then you lost also your recovery phrase, unfortunately, there's no way we can possibly help you on this case.

**Comment by DanielBoba** [comment]
Not suddenly, in the middle I use an Android up to upload the wallet, I don´t know if this affect. I can give you a reward if you offer to recover. Maybe a personal version of the app who doesn´t check this password  ? I suer, my previous password is not working and always use the same. can be a problem with node configuration and trying to find password in a different plase ? You are my last hope.

**Comment by DanielBoba** [comment]
Maybe recover 12 words somehow ? because I´m in on the wallet.

**Comment by DanielBoba** [comment]
Where can i put my recovery phrase ? I´m usiong version 0.1.2 That will be great !

**Comment by DanielBoba** [comment]
My email is danielbobadillaarg@gmail.com if you want write me

**Comment by DanielBoba** [comment]
You was 100 % right, it´s working also in the 0.1.2 version.

Many thanks
