### ISSUE TITLE
Differences in NFT information 

### ISSUE THREAD

**Issue by rodri-r** [crypto-com/chain-desktop-wallet#632]
**Describe the bug**
After minting some NFTs with the Desktop Wallet Version 0.4.2, I see some differences and missing information in NFT collection in Android DeFi Wallet Version 1.14.2.    In the desktop wallet all information shows properly on each NFT, but in the mobile version, there is an "About the Drop" and "About"  dropdown menus, which show "No description available" when clicking on them.  When minting the NFT in the Desktop Wallet, there are no fields titled "About the Drop" or "About".

**Environment and Version (please complete the following information):**
 - OS: Windows 10
 - Version [0.4.2]
 - Android 7.1.1
- Version [1.14.2]

**To Reproduce**
1. Mint an NFT in desktop wallet, including information in all fields
2. Compare the NFT in desktop wallet collection and mobile wallet collection 
3. Mobile wallet NFT view shows "About the Drop" and "About" drop down menus, with "No description available" when clicked. 
4. Destop wallet, shows "About the Drop"  information, which was filled in "Drop Description" field when minting, this information appears as "Description" in mobile wallet

**Expected behavior**
The same NFT data and information on both desktop wallet and mobile wallet collection.

**Comment by crypto-matto** [comment]
Hi @Rodri-R, content of `About the Drop` is specifically only available for NFTs minted by Crypto.com NFT marketplace. It's also a data fetched from the Crypto.com NFT marketplace itself, therefore, even the on-chain data is not containing any `About the Drop` data. That's why there's no way to mint an NFT including this info.
