### ISSUE TITLE
Problem: Add IP Blocking support on app start

### ISSUE THREAD

**Issue by cdc-Hitesh** [crypto-com/chain-desktop-wallet#721]
https://docs.google.com/spreadsheets/d/1kfTZm9qHEcybo2NwoCdgeGuh1KVODFdK5-hVvUsSfX4/edit#gid=1124696947

**Comment by crypto-matto** [comment]
May refer to JS solutions from this thread. 
https://stackoverflow.com/questions/391979/how-to-get-clients-ip-address-using-javascript
