### ISSUE TITLE
Undelgate funds not showing in wallet

### ISSUE THREAD

**Issue by amgnag** [crypto-com/chain-desktop-wallet#744]
I am using chain desktop wallet. I delegated my CRO and after one month, I undelegate my CRO. After successful undelegation, wallet is not showing history of undelegated transaction and undelegated CRO is not showing in my total CRO balance.

**Comment by HankFit247** [comment]
This is resolved in v0.5.4

**Comment by crypto-eddy** [comment]
Nice 🥳
