### ISSUE TITLE
Feature : Load all transactions types and show them in transactions history

### ISSUE THREAD

**Issue by crypto-eddy** [crypto-com/chain-desktop-wallet#799]
Currently we only have transfers transactions in transaction history (Crypto .org), but the backend API for transactions is now powerful enough to show all transactions types like delegations, undelegations, rewards withdrawals, etc, ... in a single call.

Example: https://crypto.org/explorer/api/v1/accounts/cro1vnt2jfrca4g7fnk98pth2xlqdzznnjrepljtmm/messages?order=height.desc

This task will have :
- A new way to load and persist all transactions types.
- Present them in the UI around transactions history.
- Sunset the old method

**Comment by crypto-matto** [comment]
Suggestions on UI: 
- One more transaction type tag to suggest which transaction type it is
- Add a transaction type selection filter out different types
- Add date picker section

**Comment by cdc-Hitesh** [comment]
Shall we first decide the different types of transactions?
@crypto-eddy @crypto-matto
