### ISSUE TITLE
Version Beta 0.5.4 asking for password I've never created

### ISSUE THREAD

**Issue by fabiobfava** [crypto-com/chain-desktop-wallet#803]
**Describe the bug**
Application has auto-updated (it shouldn't) to 0.5.4 and then asks for a password, wich I've never asked to create. My wallet is on my Ledger Nano X. I need to access my account and don't know how.

**Environment and Version (please complete the following information):**
 - OS: Mac OS X Mojave 10.14.6
 - Version v0.5.4 (recently released)

**To Reproduce**
Don't know how. I've never created a password to access my ledger's wallet. Now the app keeps asking for a password that I've never created.

**Expected behavior**
I don't know. It should ask me to create a password at first, then I would be able to type it and unlock my wallet.

**Screenshots**
![locked-app](https://user-images.githubusercontent.com/25873020/140938163-aaf0c045-94c6-431a-8cb5-dde59d0f4a6a.jpg)

**Additional context**
Please help me to unlock my wallet, thanks!

**Comment by crypto-eddy** [comment]
Hey @fabiobfava when you open the app for the first time it requests the password. So you might need to input the original password you used.

If you don't have it, you can uninstall and reinstall again the app, since you use Ledger based wallets, there's no risks in losing anything. You can still come back and recreate again these same Ledger wallets.

**Comment by crypto-matto** [comment]
Hi @fabiobfava, we only have 1 App Password for the Desktop Wallet. As long as you've previously installed Desktop Wallet before, you would've created a password and this would carry across different versions. Even after you've uninstalled the wallet, the local storage won't be erased & will be there when you reinstall Desktop Wallet again. 

If you've forgot your password, as long as you have the recovery keys (Standard Wallets) or wallets on your Ledger, you can always recreate your owning wallets again. 

Note: If you are looking for safely uninstall & deleting all storage in Desktop Wallet, you shall go to `Settings` => `Clear Storage` to safely delete all of your existing local storage.

**Comment by fabiobfava** [comment]
Thanks folks. I'll use TinkerTool System to uninstall all the app settings and storages (should I?), and keep only the application itself. On first install I'll then create a password (I missed this step when I've started), and hope my staked CRO will be there... Please let me know if I should keep some preference or storage file on my Mac when uninstalling. Thank you very much.

**Comment by crypto-matto** [comment]
> Thanks folks. I'll use TinkerTool System to uninstall all the app settings and storages (should I?), and keep only the application itself. On first install I'll then create a password (I missed this step when I've started), and hope my staked CRO will be there... Please let me know if I should keep some preference or storage file on my Mac when uninstalling. Thank you very much.

As long as you have your recovery mnemonic keys, or your Ledger devices, your funds will be secured & able to restore your wallets again anytime in any device. You may refer to my above comment & note for safely uninstall / reinstall the wallet.

**Comment by fabiobfava** [comment]
> > Thanks folks. I'll use TinkerTool System to uninstall all the app settings and storages (should I?), and keep only the application itself. On first install I'll then create a password (I missed this step when I've started), and hope my staked CRO will be there... Please let me know if I should keep some preference or storage file on my Mac when uninstalling. Thank you very much.
> 
> As long as you have your recovery mnemonic keys, or your Ledger devices, your funds will be secured & able to restore your wallets again anytime in any device. You may refer to my above comment & note for safely uninstall / reinstall the wallet.

As said before, I don't have mnemonic seed since my wallet is from my Ledger Nano X. When I open the application for the first time, after creating the App Password succesfully, if I select Restore it asks for a mnemonic seed (wich I don't have), and if I select Create Wallet, then I select the "Want to create with hardware wallet?" option, select "ledger" as wallet type and "0" as Address Index (I assume this was the one I've used before, as it's the first). I select "Mainnet" and hit "Create Wallet".

At this point it asks to connect to Crypto.org App on my Ledger (wich is open), I click Connect and it goes further. Then it asks to connect to Ethereum App on my Ledger. But as it's not opened, it fails to connect, and then I have this screen with the error (derivation path may be incorrect):

![cro-error](https://user-images.githubusercontent.com/25873020/140998311-de90e613-db3d-4bd9-9612-5bcda8bf1266.jpg)

Please let me know how I should proceed, thank you very much.

**Comment by crypto-matto** [comment]
You may purge the local storage of Desktop Wallet by deleting the folder {name}.leveldb & {name}.blob, which are located at: 
MacOS: /Users/{username}/Library/Application Support/chain-desktop-wallet/IndexedDB
Windows: c:\Users\{username}\AppData\Roaming\chain-desktop-wallet\IndexedDB

Then you're able to reset the password & restore your wallets again.

**Comment by fabiobfava** [comment]
Nope, crypto-matto. I've done that and the same happens. It cannot connect to Ethereum being inside Crypto.org application on my Ledger. This won't work, same situation happens. I'll keep looking forward to be able to restore my funds and staked funds from my account to the Beta App. Thanks!

**Comment by fabiobfava** [comment]
Hey folks. I've managed to re-create it all by reinstalling the prior version. Anyway it cannot find the ETH App since the CRO.org App is opened. Then it creates a totally new wallet, with a different address and ZERO funds and stake. There must be something wrong, my wallet was created on my Ledger Nano X so it should be restored! Please help me I have no funds now!

**Comment by crypto-matto** [comment]
Hi @fabiobfava , please use the latest version and restore your ledger wallet. 

Actually there are 2 steps during the Ledger wallet creation: 
1. The first step you have done correctly, which is open `Crypto.org` App and click `Connect`
2. The second step is to exit `Crypto.org` App and open the `Ethereum` App instead to continue the Cronos wallet creation. When `Ethereum` App is opened, click `Connect` to finish. 

Regarding to your different address, Ledger uses a Derivative Path mechanism to generate addresses. The Derivation Path refers to all of the possible key pairs that can be generated from the seed phrase inside your Ledger Device. Every single `Address Index` input will result in a different Address. So it is highly possible that you have input a different `Address Index` from your previous one during your Ledger Wallet restore. Please use the same `Address Index` as the one you input previously. (Our default `Address Index` is `0`)

**Comment by fabiobfava** [comment]
Hey @crypto-matto thank you for the infos. It's not working as expected.

1) I've managed to restore my old wallet (and funds and staked funds) from a backup.

2) What you propose doesn't work: as I exit the Crypto.org App and open the Ethereum App on my Ledger, as I re-open the Crypto.org App to connect, it asks me to connect to Crypto.org App first, but ETH App is open on the Ledger. So it won't work in any possible way.

3) The App now updates itself automatically, so I can't keep using the 0.4.2 that was working.

4) The "Lock" button now is so explicit that users may click by mistake, locking their funds as it happened to me.

So in my opinion the new version is null, as it will block user's funds by one way or other. It should be possible to NOT update or to SKIP this version, since it makes all this.

To make it worse, all my CRO.org funds are staked, so I have no funds to un-stake it, move it out of the app, and then create a new wallet with a password and send back my funds to my wallet. I feel a bit lost now. Everything was working fine up to 0.4.2 but now it got all messy, and every now and then my funds are lost or locked by a password I don't have. I need to find a solution, please help me.

**Comment by fabiobfava** [comment]
Hey @crypto-matto I've managed to do it by restoring my wallet (with all funds) from my external backup.

Then I've done the steps you've said, and managed to connect both cro.org and eth onto the MacOS Application. So now I can see the Cronos Bridge, and my funds and staked funds are still there.

The problem now is that I don't know the password for that wallet. As I remember I was never asked to create one because my wallet is on my Ledger Nano X. To make it worse I've delegated all my funds to stake, and I have no funds to pay the taxes to un-stake it.

I'd need to move all my funds out, then create a new wallet with a proper Password, then send my funds to the new wallet in order to never get it locked for missing the password. Is there any way to reset the password without knowing the actual one?

Please help me, now the "Lock" button is so evident that at some point I may click again to lock, and then I don't know how to unlock. I'd also like to make a copy of the mnemonic seed for this wallet, but I cannot find it.

**Comment by crypto-matto** [comment]
> Hey @crypto-matto I've managed to do it by restoring my wallet (with all funds) from my external backup.
> 
> Then I've done the steps you've said, and managed to connect both CRO.org and ETH onto the MacOS Application. So now I can see the Cronos Bridge, and my funds and staked funds are still there.
> 
> The problem now is that I don't know the password for that wallet. As I remember I was never asked to create one because my wallet is on my Ledger Nano X. To make it worse I've delegated all my funds to stake, and I have no funds to pay the taxes to un-stake it.
> 
> I'd need to move all my funds out, then create a new wallet with a proper Password, then send my funds to the new wallet in order to never get it locked for missing the password. Is there any way to reset the password without knowing the actual one?
> 
> Please help me, now the "Lock" button is so evident that at some point I may click again to lock, and then I don't know how to unlock. I'd also like to make a copy of the mnemonic seed for this wallet, but I cannot find it.

Hi @fabiobfava , I'm glad that you've found the way & able to secure all your funds again. 

In order to export your mnemonic seed for a specific wallet (only eligible to Standard Wallets), you are required to enter your App Password. Here is the guide [https://crypto.org/docs/wallets/desktop_wallet.html#_7-3-export-your-wallet-recovery-phrase](https://crypto.org/docs/wallets/desktop_wallet.html#_7-3-export-your-wallet-recovery-phrase) . 
If you have forgotten the password, there's no way you could export the mnemonic seed by security reasons. It's always important to write down your mnemonic seed or private key and keep it safe & secure. 

You may also visit this guide on how to reset your password. Proceeding this step will not require your App Password. 
https://crypto.org/docs/wallets/desktop_wallet.html#_7-4-clear-your-storage
Please also note that if you `Clear Storage`, all your local storage will be cleared & you have to restore all your wallets one by one again.

**Comment by fabiobfava** [comment]
Hey @crypto-matto thanks for your reply!

> In order to export your mnemonic seed for a specific wallet (only eligible to Standard Wallets), you are required to enter your App Password. Here is the guide https://crypto.org/docs/wallets/desktop_wallet.html#_7-3-export-your-wallet-recovery-phrase . If you have forgotten the password, there's no way you could export the mnemonic seed by security reasons. It's always important to write down your mnemonic seed or private key and keep it safe & secure.

Since my wallet was created using my Ledger Nano X, I assume this doesn't apply to me, right?

> You may also visit this guide on how to reset your password. Proceeding this step will not require your App Password. https://crypto.org/docs/wallets/desktop_wallet.html#_7-4-clear-your-storage Please also note that if you `Clear Storage`, all your local storage will be cleared & you have to restore all your wallets one by one again.

If I Clear my Storage, I assume it will generate a different wallet address due to the derivation path thing. I'd like to keep my actual address, since it's known by some 3rd party that I'd like to keep this address.

I've been trying this option earlier, but after re-creating my wallet was completely empty, no funds and no stake. So I'd rather move out all those funds before trying this operation, since I don't want to lose my funds.

I'll back up again my system before trying this procedure just in case, and then I get back with my results.

Thank you very much, cheers!

**Comment by fabiobfava** [comment]
Hey there. I've clicked again by mistake on the "Lock" button. Now I cannot unlock my wallet, wich have all balance staked. I've tried restoring to a new wallet, but it comes completely empty: no funds, no stake. I'd really need to be able to restore a wallet WITH my funds on it, please help me!
