### ISSUE TITLE
Bridge : Allow users to specify manually destination address during bridge transactions

### ISSUE THREAD

**Issue by crypto-eddy** [crypto-com/chain-desktop-wallet#805]
- Update the UI to present a destination address UI input. (@crypto-matto )

- Handle the custom UI address input on the backend bridge service. ( @crypto-eddy )

We can use this https://cronos.crypto.org/bridge as reference.

**Comment by JJWW34** [comment]
the UI can still keep the auto-generated cronos address but add a "Or" option to input another destination address.
