### ISSUE TITLE
Problem: Potential incorrect delegation info after staking operations

### ISSUE THREAD

**Issue by crypto-matto** [crypto-com/chain-desktop-wallet#812]
## Problem 
The community team has passed over a weird issue - The user has made a few undelegations and they look successful in the explorer. But nothing changed on his desktop wallet UI. Clicking the refresh button doesn't solve the problem for the user. 
Community team reported similar issues in previous version before.

Address: `cro1c3p2v2r9lnsnh0z06dac5peq4rczy3jjj5x6fn`
Screenshots after undelegation:
![image (3)](https://user-images.githubusercontent.com/74586409/141285474-c6089808-da8d-45d8-80fd-c77378c48b83.png)
![image (4)](https://user-images.githubusercontent.com/74586409/141285475-04125f67-6c57-4229-a53d-1b9f2ed14c0a.png)
![image (2)](https://user-images.githubusercontent.com/74586409/141285480-3e3fb3f3-ed78-4650-b88b-8a62749a7090.png)

## Possible cause
The user is probably not performing undelegation on Desktop Wallet, as we cannot reproduce the issue if we perform all staking operations with Desktop Wallet only. They may be doing it from somewhere else, and the Desktop Wallet is not fetching the latest staking list if they didn't perform any staking-related operations from our side & we display list from local storage.

## Study
See whether could reproduce the issue by:
- Perform some staking in Desktop Wallet
- Perform undelegation from another wallet client (may be DeFi wallet)
- See if there are any validation info unmatch
- If so, try to revise on the validation fetching mechanism on our side

**Comment by cdc-Hitesh** [comment]
Cause:
- The delegation API returns 404 when there are no active delegations.
