### ISSUE TITLE
Problem: WalletService.ts is deprecated

### ISSUE THREAD

**Issue by crypto-matto** [crypto-com/chain-desktop-wallet#813]
## Problem
`WalletService.ts` is deprecated & refactored into `TransactionSenderService.ts` and `TransactionHistoryService.ts` in #771. 

While `WalletService.ts` should be removed in #771, `WalletService.ts` was added back in merging #785, with a lot of duplicated functions with the refactored files.

**Comment by XinyuCRO** [comment]
the purpose of #771 is not to remove `walletService`, but to separate some logic into small pieces, like `txHistoryManager` `txSenderManager`, etc, and these managers are not intended to be accessed outer, the main interface for wallet related logic is still `walletService` 

am I understanding this right? cc @cdc-Hitesh

**Comment by crypto-matto** [comment]
> the purpose of #771 is not to remove `walletService`, but to separate some logic into small pieces, like `txHistoryManager` `txSenderManager`, etc, and these managers are not intended to be accessed outer, the main interface for wallet related logic is still `walletService`
> 
> am I understanding this right? cc @cdc-Hitesh

Yes confirmed with @cdc-Hitesh. Sorry that I overlooked the commit. You may just delete those duplicated functions. Thanks.

**Comment by XinyuCRO** [comment]
checked the #785, there are no changes related to `walletService` and any refactored related files, also checked the codebase, haven't found any duplication @crypto-matto

**Comment by cdc-Hitesh** [comment]
Sounds great. 🪨
