### ISSUE TITLE
Research work on how to inject a Web3 provider in a browser, to make a browser support web3 dapps. 

### ISSUE THREAD

**Issue by XinyuCRO** [crypto-com/chain-desktop-wallet#818]

**Comment by crypto-matto** [comment]
In case of DeFi wallet:
1. It establishes a connection between the phone (DeFi Wallet App) and the DeFi Wallet chrome plugin, with a QR code scanning
2. The private key is always storing on the phone only
3. When clicking any CTA buttons, the plugin sends the raw transaction to the phone and ask for corresponding signature
4. When you confirm transaction on the phone, it sends back the signature to the plugin
5. The plugin will submit the signed transaction & broadcast the chain just like metamask

**Comment by XinyuCRO** [comment]
Closed by https://github.com/crypto-com/chain-desktop-wallet/pull/840
