### ISSUE TITLE
Enhancement: Allow Input of our own Metamask Address

### ISSUE THREAD

**Issue by roleerob** [crypto-com/chain-desktop-wallet#839]
**Is your feature request related to a problem? Please describe.**

Yes, when attempting to use the Cronos Bridge (EVM-based, right?), the ETH address is already specified and I see no link between it and the ETH addresses available to me on my Ledger-backed Metamask.

**Describe the solution you'd like**

Having ledger-backed addresses is essential to my sense of at least some safety and security in transacting with cryptos.  Just like with other EVM-based blockchains (BSC, Polygon, Avalanche, Fantom ...)  I would like to be able specify the address to which my crypto will be sent.

**Describe alternatives you've considered**

If there is an alternative, I do not know what it would be. 

**Additional context**

**Comment by roleerob** [comment]
This morning, upon opening my Chain Desktop Wallet, got prompted to upgrade to v0.5.6, which I did.  Upon opening it and STILL trying to get some of my CRO stake into Cronos, across the "bridge," I was pleasantly surprised to find I could now check "Send funds to a custom destination address."

Wel ...  It didn't work!!  It ended up sending to a different address, I assume the one which has been "chosen" for me, as per my original request above! 🙁  Now I have CRO "stuck" at that address.

Guess I will find out shortly if I can "Send" from inside your wallet and still in 2 steps vs. 1, get it to my preferred Ledger-backed address.

**Comment by roleerob** [comment]
Nope, "Send" does not work ...

![image](https://user-images.githubusercontent.com/31572169/143288166-14957ad4-79d3-4902-a6db-8f2ad1196991.png)

Funds are "stuck" ...

**Comment by roleerob** [comment]
Yes, in the event you ask the question, I used the ETH app on my Ledger, not the CRO app ...

That said, I think you would help by providing a clear dialog, when sending from your CRONOS account, that you need to be sure and use the ETH app.

**Comment by crypto-matto** [comment]
Thanks for your bug report 🙏🏻🙏🏻 We've acknowledged that the custom deposit address doesn't work on Ledger devices yet. It's working perfectly on standard wallets. We'll fix this ASAP.
