### ISSUE TITLE
Problem, v0.5.6: Wallet CRO Balance Not Accurate ...

### ISSUE THREAD

**Issue by roleerob** [crypto-com/chain-desktop-wallet#841]
**Describe the bug**

My CRO balance under "Assets" is incorrect.  Specifically, it does not show the results of the last transaction on the Crypto.org Explorer.  This has a date / timestamp over 10 hours ago.!  If it helps, the transaction with an IBF "time-out reversal" of a "Send" transaction executed yesterday (Nov. 24th).

As a secondary, less important issue (to me, at least) is that the price on the "Assets" is also not current.

Are both related to some issue with an internal refresh mechanism?

**Environment and Version (please complete the following information):**
 - OS: [e.g. Windows, Mac, Linux] Windows 10 Pro
 - Version [e.g. v0.0.1] v0.5.6

**To Reproduce**

**Expected behavior**

Stating the obvious, I would like both the amount and value of my assets to be accurate!

**Screenshots**

**Additional context**

**Comment by roleerob** [comment]
Hmmm.  In the time since first opening my wallet, to writing the above, probably 20 minutes have elapsed.  In that time, my wallet now DOES show the correct amount, but the price is still way off.  I know there are variances between different pricing sources, but I don't think it is anywhere near the gap showing now.  The pricing appearing in the wallet appears old, by at least (guessing) 12 hours.

**Comment by hschfu** [comment]
I encountered the same problem with following env.
OS:  Windows 10 Pro
Version:  v0.5.6
Again, click refresh button does not fix this issu
![螢幕擷取畫面 2021-11-29 102758](https://user-images.githubusercontent.com/3711900/143799327-96d7e873-6e94-49e4-abff-2481839e5317.png)
e.

**Comment by rosskevin** [comment]
#868 may be the same issue.
