### ISSUE TITLE
Critical Enhancement Request:  Add memo field to Address Book for Crypto.com Android App Transfers of CRO!!

### ISSUE THREAD

**Issue by roleerob** [crypto-com/chain-desktop-wallet#844]
**Is your feature request related to a problem? Please describe.**

Your address book lacks an essential field - a Memo field.  As you almost certainly know (or should know), the Crypto.com Android App cannot receive a CRO deposit, without the right Memo #!  As the Address Book is now, I have added this address, but it opens me open to the possibility of forgetting the need to manually add the Memo #, which could be disastrous ...

**Describe the solution you'd like**

There needs to be a an additional optional Memo field added to the records stored in your wallet's Address Book.

**Describe alternatives you've considered**

The only alternative is to simply not store this particular (often used!) address in the Address Book at all, to avoid the potential of thinking I can simply click on the Address and carry on, forgetting this essential piece of info is missing!

**Additional context**

**Comment by crypto-matto** [comment]
This is a sound suggestion which we had lack of consideration. We'll be adding support for it in near release. In the meantime, please always make sure you add memo into the sending address if it's an exchange deposit address.
