### ISSUE TITLE
Assets | CRO | Price | £ GBP - is Incorrect

### ISSUE THREAD

**Issue by Techboy** [crypto-com/chain-desktop-wallet#845]
**Describe the bug**
Navigate to:

- Assets
- CRO
- Price
- £ GBP

It currently shows **£0.71** GBP when the CDC app shows it as **£0.5651** and https://crypto.com/exchange/trade/spot/CRO_USDT shows it as **$0.74318**

This is true of CRO (Crypto.org) and CRO (Cronos Beta).

**Environment and Version (please complete the following information):**
 - OS: Windows
 - Version 0.5.6

**To Reproduce**
Navigate to:

- Assets
- CRO
- Price
- £ GBP

**Expected behavior**
The value should be correct.

**Comment by crypto-matto** [comment]
We'll be looking into this. So far we haven't spotted this issue on our side yet. 
P.S. We're using Coinbase API for retrieving the market data. There might be a delay in updating with their market value from their API.

**Comment by crypto-matto** [comment]
### Update
We'll soon be using our own Crypto.com Price API for retrieving the market data instead. Probably will be updated & released next week.
