### ISSUE TITLE
Unbonding Delegation 'Remaining Time' counter goes positive after elapsed staking time

### ISSUE THREAD

**Issue by Techboy** [crypto-com/chain-desktop-wallet#859]
**Describe the bug**
Once the 28 day unbonding period has elapsed, the Unbonding Delegation 'Remaining Time' counter goes positive. This can be confusing to people as they might think this how much time is remaining.

OS: Windows
Version 0.5.7

**To Reproduce**
After a 28 day unbonding period:
1. Go to: Staking
2. Go to: Delegation Management
3. Select: View Unbonding Delegation
4. The 'Remaining Time' counter shows a positive value (i.e. the amount of time elapsed since the unbonding period ended). It should show 'Unbonding complete'

**Expected behavior**
The 'Remaining Time' counter should show 'Unbonding complete'

**Comment by crypto-matto** [comment]
<img width="466" alt="螢幕截圖 2021-12-14 下午6 19 03" src="https://user-images.githubusercontent.com/74586409/145979552-f7265210-447b-4466-9b86-1792f7c9385d.png">

I believe our current fields setup are clear enough in demonstrating:
- Remaining Time: Remaining Time until the unbonding finishes
- Completion Time: The exact time when the unbonding finishes

I may add a Tooltip on these 2 fields better explaining the situation though.

**Comment by Techboy** [comment]
My issue is that after the time has elapsed, the timer goes positive, which is confusing.
So for you, on Thur Jan 06 2022, 17:20:30 the 'Remaining time' will be 1 day.

Mine shows 'Time Remaining' 12 days, but it ended on 2nd December.

![Screenshot 2021-12-14 102633](https://user-images.githubusercontent.com/618038/145980787-93200480-90e6-409d-8b7d-0a0a0032b3dd.JPG)
