### ISSUE TITLE
Problem: Crypto.org wallets balance is showing zero after mainnet upgrade

### ISSUE THREAD

**Issue by crypto-matto** [crypto-com/chain-desktop-wallet#865]
## Problem
After the Mainnet `chain-maind v3.3.2` upgrade, the Crypto.org wallet balance retrieval API `/cosmos/bank/v1beta1/balances/[address]/[denom]` is failing on Mainnet, which results in a zero balance. 
e.g. [https://mainnet.crypto.org:1317/cosmos/bank/v1beta1/balances/cro1phlk2ypy0t349fkdmahtlsq456kng6m5xm3utx/basecro](https://mainnet.crypto.org:1317/cosmos/bank/v1beta1/balances/cro1phlk2ypy0t349fkdmahtlsq456kng6m5xm3utx/basecro)
```
{
  "code": 12,
  "message": "Not Implemented",
  "details": [
  ]
}
```
This leads to the Desktop Wallet unable to perform any transactions as the available balance is always zero.

## Solution
Use `/cosmos/bank/v1beta1/balances/[address]` and parse the balance instead.
e.g. [https://mainnet.crypto.org:1317/cosmos/bank/v1beta1/balances/cro1phlk2ypy0t349fkdmahtlsq456kng6m5xm3utx](https://mainnet.crypto.org:1317/cosmos/bank/v1beta1/balances/cro1phlk2ypy0t349fkdmahtlsq456kng6m5xm3utx)
```
{
  "balances": [
    {
      "denom": "basecro",
      "amount": "2263483795600"
    }
  ],
  "pagination": {
    "next_key": null,
    "total": "1"
  }
}
```

**Comment by crypto-eddy** [comment]
Is this issue coming from us or it's a chain related problem ?

If it's a chain related problem, it should be fixed from that side.

**Comment by crypto-matto** [comment]
> Is this issue coming from us (desktop client) or it's a chain related problem ?
> 
> If it's a chain related problem, it should be fixed from that side.

I believe it’s a hidden additional API breaking change for `chain-maind v3.3.2`, which we might’ve overlooked.

**Comment by Atomicprogress** [comment]
I have the same problem, I did a Withdraw Reward of staking and the total balanced became 0 CRO!!! O_O
going to https://crypto.org/explorer/account/ luckily I see my balance correct !! 
...I was taken a hit !! 
...Now?
