### ISSUE TITLE
Usable balance not available in the app

### ISSUE THREAD

**Issue by gsempe** [crypto-com/chain-desktop-wallet#868]
**Describe the bug**
All my wallet is synchronized but when I try to stack my usable balance, it is 0 even though there are > 230 CROs

**Environment and Version (please complete the following information):**
   - OS: Mac 10.15.6 Catalina
 - v0.5.7

**To Reproduce**
1. Go to 'Stacking'
2. Click on 'Delegate funds'
3. Scroll down to 'Delegate amount'
4. The available CRO is 0.0000 CRO ($0.00)

**Expected behavior**

**Screenshots**

<img width="832" alt="Screenshot 2021-12-07 at 14 27 19" src="https://user-images.githubusercontent.com/1011479/145037541-fb3b5482-d8e0-4d12-ae85-3590270fc264.png">

**Additional context**
My usable balance is above 230 CRO.

**Comment by gipetkov** [comment]
Same problem:
Windows 10
v.0.5.7
Can't delegate, can't send - show cro amount - 0

**Comment by kbowie** [comment]
got the same issue, usable balance in the blockchain is correct, however it doesn't appear as a balance inside the wallet, but received transaction appears in the history

<img width="964" alt="Screenshot 2021-12-07 at 15 47 18" src="https://user-images.githubusercontent.com/2580564/145061225-bc4ec8a5-2630-45fa-bfff-2cd2777a23ea.png">
<img width="898" alt="Screenshot 2021-12-07 at 15 47 24" src="https://user-images.githubusercontent.com/2580564/145061233-3e9a969a-20cd-417a-958d-4d64fd569034.png">

**Comment by HankFit247** [comment]
Same issue here as well.

Windows 10 Pro
V0.5.7

Withdraw Rewards:
https://crypto.org/explorer/tx/A91341BBC14DD4F31550F3D4E654F5545D99DF256B10FCB55414557A9F6BDA56

Withdraw Funds from Crypto.com App to DeFi Wallet.
https://crypto.org/explorer/tx/8A84DD5B78D5395CB827B2D84031610299B4E96E5FEE29FAC759F1EBCAF9D3C2

When I go to Delegate Funds to my chosen Validator, balance shows as ZERO.

**Comment by rosskevin** [comment]
Same as @kbowie.  New wallet, backed by Ledger with 1 CRO (native) transferred to `crypto.org chain`.   Transaction successful and visible with no change in balance on `Assets` or `Home`.

OSX 11.6

**Comment by Techboy** [comment]
I have the same issue. Withdrawing a reward was successful but it doesn't show in the app despite refreshing, closing and starting it. The CRO does show in https://crypto.org/explorer/

Windows 11
v0.5.7

**Comment by cpi015** [comment]
Same as everyone here, glad to find out i'm not the only one facing this issue :)

Like everyone, crypto.com mainnet chain balance on the explorer is fine but the app show 0.

It should be related to the client side not syncing properly. I guess it should be resolved soon once the information is coming back synced again to our Desktop Wallet Clients.

I've tried to load previous version V0.1.0 just to see but balance is 0 as well

Wonder how much time it'll take to be solved tho !

Windows 10
V0.5.7

**Comment by labnotes** [comment]
Bug still persists. Desktop Wallet claiming staking rewards doesn't show up in delegated funds tab to restake. When viewing the same account on defi wallet on the phone, stake rewards show and able to restake.

**Comment by crypto-matto** [comment]
We're sorry for the inconvenience caused and we've addressed the issue due to the Crypto.org mannet upgrade yesterday 🙏🏻 An update patch will be launching soon. Stay tuned.

**Comment by petercockroach** [comment]
Is it possible to pull down the latest release?

**Comment by crypto-matto** [comment]
We've just resolved the issue and launched v0.5.8 release. You may either: 
- Wait for the auto-updater appears in the app 
- Install the latest v0.5.8 version from our Desktop Wallet (Beta) website directly:  https://crypto.org/desktopwallet
- Download latest v0.5.8 version from our GitHub Releases: https://github.com/crypto-com/chain-desktop-wallet/releases
Choose the correct file extension to download based on your OS.

At the same time, we've prepared a Christmas Logo for you. We hope that you'll like it 🎄 🤶 

Once again sorry for the inconvenience caused 🙏🏻🙏🏻🙏🏻

**Comment by Techboy** [comment]
All works now - I auto-updated to v0.5.8 and was able to 'Withdraw Reward' and Delegate Funds. Thanks 👍

**Comment by cpi015** [comment]
Hello, Everything works again !! I'm really impressed how quick the process has been to receive the update.

BIG up to the dev team 💯, Cheers from a C,C++ Dev !

Wish good year end and XMAS to the whole community 🎄 🤶

Kind regards, Chris 👍👍👍

**Comment by rosskevin** [comment]
@crypto-matto this is unresolved for me and should be reopened.


<img width="1283" alt="bug" src="https://user-images.githubusercontent.com/136564/145309651-32e045a4-65e3-40a0-813d-379a743fdbef.png">

**Comment by rosskevin** [comment]
Sorry!

@crypto-matto it IS resolved, I was not patient enough for the balance to update.

The correct balances are now showing.  I'm sorry to jump the gun, this app is new to me and I'm not yet used to the latency.
