### ISSUE TITLE
Can't Verify Cronos address on Ledger Nano X

### ISSUE THREAD

**Issue by OsandaMalith** [crypto-com/chain-desktop-wallet#870]
Seems like the CRO app in the ledger doesn't support verifying the Cronos address from the desktop wallet.

![image](https://user-images.githubusercontent.com/4497190/145274259-194bed30-4e67-4e3c-87ae-bec21ca5e4c9.png)

**Comment by crypto-matto** [comment]
Hi @OsandaMalith, you’ll need to open Ethereum App instead for CRONOS address

**Comment by OsandaMalith** [comment]
@crypto-matto Thanks! Got it. I hope they integrate this into the CRO app to avoid confusion. Also if I send other tokens in the Cronos chain to my desktop wallet address, will it be displayed?

**Comment by crypto-matto** [comment]
@OsandaMalith Nope, CRC20 tokens are not supported yet so they won't be displayed. But we're bringing this support to Desktop Wallet & very likely to be released soon. Stay tuned!

**Comment by OsandaMalith** [comment]
Sounds good! @crypto-matto
