### ISSUE TITLE
CRO From Coinbase Pro to Crypto.org Chain Desktop App Help

### ISSUE THREAD

**Issue by T-Bone21** [crypto-com/chain-desktop-wallet#872]
I am not the greatest at being tech-savvy when it comes to CRO but I am trying to learn and any help would be greatly appreciated because I cannot find the answer on Reddit, YouTube, or Discord.  

So, I tried transferring some CRO from Coinbase Pro to the Crypto.org Chain Desktop app which is synced to my Ledger and the funds never arrived but they are in the Ledger Live app. How do I get the funds to the Crypto.org Chain Desktop app because I thought I originally was sending them there in the first place?

If you could give me step-by-step instructions or share a link that describes how to accomplish this that would be awesome.              

Thanks in advance.

**Comment by cpi015** [comment]
Hello T-Bone, from what i understand you have an ERC20 version of your CRO that you see under the asset on your Ethereum address in ledger live.

You need to this : 
* transfer those ERC-20 CRO token (using Ethereum blockchain, from your ledger app) to crypto.com exchange or crypto.com app (support multiple network)
* You can then transfer your CRO from crypto.com exchange or APP to your Desktop wallet (blockchain CRO). You can see that the blockchain CRO has different address type then Eth adress that always start with 0x...
* Then you'll be able to see and interact with your funds on the dekstop app wallet and even transfer to Cronos network with the same token (CRO) from there ;)

Wish you good luck 

Kind regards, Chris
