### ISSUE TITLE
Random Error signing a transaction with my Ledger nano X

### ISSUE THREAD

**Issue by kotbrei** [crypto-com/chain-desktop-wallet#874]
Hi as i was testing this wallet with my new ledger nano x i transfered 10 CRO to the wallet and wanted to transfer them back to my Crypto.com App on my iPhone. Transfering to the wallet was super easy and fast but i cant sign the transaction back withouth getting this error: 

![image](https://user-images.githubusercontent.com/96019607/145723958-48988fe2-fb6a-4aca-a485-afa4ec5750dc.png)

The problem is, the message is so genereic that i dont know what my mistake is, can you help me out?

**Comment by crypto-matto** [comment]
Hi @kotbrei , this is usually because you're sending all CRO & without leaving any CRO for transaction fee. See if you're able to send the funds with, e.g. 9.9 CRO?

**Comment by kotbrei** [comment]
Thanks a lot @crypto-matto , that worked!
