### ISSUE TITLE
Problem: Missing support of DelayedVestingAccount rewards withdrawal

### ISSUE THREAD

**Issue by crypto-matto** [crypto-com/chain-desktop-wallet#879]
## Problem
Missing support of [DelayedVestingAccount](https://docs.cosmos.network/master/core/proto-docs.html#cosmos.vesting.v1beta1.DelayedVestingAccount). This function would be used for CrossFire dryrun participants (around 200-300), which they are eligible for redeeming their rewards recently.
![vestingAccount](https://user-images.githubusercontent.com/74586409/146151639-9735579e-db13-4dbc-a76d-791693a78d4b.png)
- It is uncertain whether the function is deprecated or was not supported from the beginning

**Comment by cdc-Hitesh** [comment]
I doubt whether we ever supported this function.
There is no such method in Chain JS Lib as well.
