### ISSUE TITLE
Cannot withdraw my CRO rewards using my ledger

### ISSUE THREAD

**Issue by davidmontoya60** [crypto-com/chain-desktop-wallet#886]
Hello, 
I need help withdrawing my CRO staking rewards. I got the following message using my ledger: 
The reward withdrawal transaction failed. Please try again later.
- getPubKey fail
- TypeError
- cannot open device with path IOService

**Comment by zeroworry** [comment]
I'm having a similar issue with Staking CRO. I get the same message but I'm on Windows 11
The staking transaction failed. Please try again later.
- getPubKey fail
- Error
- App does not seem to be open

The app in my ledger nano X is open (ethereum)

**Comment by crypto-matto** [comment]
Hi @zeroworry, for CRO staking reward, you'll have to open Crypto.org App on Ledger instead. 
We'll be revising the Ledger connection UX, putting more indications, as to avoid confusions among users.
