### ISSUE TITLE
Bug: Unexpected behavior when leaving DApp Browser

### ISSUE THREAD

**Issue by crypto-matto** [crypto-com/chain-desktop-wallet#901]
### Issue
While a user opened a DApp, when clicking on `DApp Browser` on the navbar, it pops up this message, a notification pops up asking user whether he/ she wants to `Leave`. But clicking `Leave` would stay in the same page without anything happening. 

<img width="376" alt="Screenshot 2022-01-04 at 6 28 32 PM" src="https://user-images.githubusercontent.com/74586409/148045563-5c0a98e2-cf33-4a70-aa2e-26837611d6f3.png">

The same situation happens in `Cronos Bridge` as well.
### Expected behavior
The user shall be going back to DApp list.

**Comment by mrdeakapants** [comment]
Bush

**Comment by mrdeakapants** [comment]
Crap
