### ISSUE TITLE
DApps Browser missing

### ISSUE THREAD

**Issue by SimonZ80** [crypto-com/chain-desktop-wallet#904]
Hi,
just a question: i can't see the DApps browser in my wallet. Why?
I'm on Windows 11 64bit 
CHAIN DESKTOP WALLET v0.6.

![Screenshot](https://user-images.githubusercontent.com/97128356/148121227-ff1da62d-0890-4613-8d1b-f9873002a102.jpg)
3

**Comment by crypto-matto** [comment]
Hi @SimonZ80, sorry that Ledger wallets are not yet supported on the DApp browser. We shall support it in our future releases. Stay tuned.

**Comment by SimonZ80** [comment]
Ok thanks for the clarification!
