### ISSUE TITLE
v0.6.5 Sort Validator List

### ISSUE THREAD

**Issue by HankFit247** [crypto-com/chain-desktop-wallet#943]
When Staking, previous to version 0.6.5, you could click in the Headers on the Validator List to sort them.  For example, by Commission.

Sort Feature is now broken in 0.6.5

**Environment and Version (please complete the following information):**
 - Windows 10 Pro 10.0.19043 Build 19043
 - Wallet 0.6.5

1. Go to Staking
2. Click on Delegate Funds
3. Click on the blue Validators List icon
4. Click any header

**Comment by crypto-matto** [comment]
Hi @HankFit247, 

We intended to remove the sort headers.

There were feedbacks from chain validators which they wish to change the validator list ordering to give better chance for smaller validators an opportunity to get 'noticed', and for a better decentralization.

The current arrangement on hiding of sort headers, & new sorting logic were made after design consideration from DeFi Wallet. Desktop Wallet sync with this approach.
#908
