### ISSUE TITLE
Duplicated validator list in delegation

### ISSUE THREAD

**Issue by llyzs** [crypto-com/chain-desktop-wallet#952]
I have only one validator to delegate to and I regularly delegate new funds to the same validator. After a recent update my wallet now shows up two rows of the same validator, with the exact same amount. Today when I delegate more funds, only one of them shows new accumulated amount, the other remains unchanged.

![image](https://user-images.githubusercontent.com/610304/150631081-a5b434db-8969-4c85-b88b-3d24a56432c5.png)

**Comment by crypto-matto** [comment]
Hi @llyzs, so far I couldn't reproduce this issue on my side. But if you're frustrated with the existing situation on your side, you may restore the wallet once again and the records should become correct again.

**Comment by llyzs** [comment]
OK I cleared storage and restore wallet, and it is now back to normal. Thanks for the suggestion.
