### ISSUE TITLE
Unable to Sign On Ledger for LP tokens removal

### ISSUE THREAD

**Issue by Loo0201** [crypto-com/chain-desktop-wallet#973]
**Describe the bug**
Hi. I have an urgent issue with Withdrawal of my LP tokens from the Liquidity Pool from VVS Finance, MM Finance back to Crypto.org chain desktop wallet. The ledger works well for signing all other transaction such as enable, swap, stake and unstake. However for the purpose of removal of LP tokens from liquidity pool, there is no prompts on the ledger while the webpage is waiting for signing confirmation. 

**Environment and Version (please complete the following information):**
 - OS: mac
 - Version v0.6.7

**To Reproduce**
Attempt to remove LP tokens from liquidity pool to a crypto.org chain wallet that was set up with Ledger hardware wallet

**Expected behavior**
Unable to complete removal of LP tokens back to wallet.

**Comment by crypto-matto** [comment]
Hi @Loo0201, the issue is acknowledged. Will fix this. Thanks for your report. 

### Issue
The remove LP tx is not triggering a confirmation on Ledger, and the app is asking for a password. May be the remove LP type tx is not yet handled with Ledger.

**Comment by Loo0201** [comment]
Hi all. May I know if this has been resolved?

Thanks much.

Regards
Martin

**Comment by XinyuCRO** [comment]
@Loo0201 This issue has been fixed on the `dev` branch and will be landed on the next release, stay tuned
