### ISSUE TITLE
Failed to broadcast delegate transaction with ledger

### ISSUE THREAD

**Issue by alsora** [crypto-com/chain-desktop-wallet#975]
**Describe the bug**
Hi, I was trying to delegate CRO.
I use a ledger nano  X, I was able to confirm that I was connected and I was able to authenticate the transaction on the ledger, however, after acknowledging the transaction on the ledger, the crypto.org chain app was showing a 403 error: failure to broadcast.

I tried for ~30 minutes, rebooting the computer, the ledger, etc.
I tried again after a few hours and had the same issue again.
This time I also tried something different: I changed the amount of CRO to delegate into an integer amount (e.g. 100 CRO vs the 100.5 I was trying to delegate before).
As soon as I changed the amount to an integer, the operation succeeded.
Not sure if it was a coincidence but it looks like it was not.
I already had tried to change the amount, but always keeping some decimals.

**Environment and Version (please complete the following information):**
 - OS: Linux
 - Version 0.6.7

**Comment by crypto-matto** [comment]
Hi @alsora, can you try with our latest release v0.6.9? 
We've just updated the electron builder package & Windows users have resolved the Ledger connection issue. See if it works well for you on Linux as well.
