### ISSUE TITLE
Cannot connect to Ledger after 0.6.8 update

### ISSUE THREAD

**Issue by Highvale** [crypto-com/chain-desktop-wallet#989]
Hi Team,

I use my ledger nano s daily to restake my rewards, however immediately after installing your latest 0.6.8 wallet update, my desktop app is no longer able to detect my ledger nano s. I can confirm that Ledger Live works fine and your CDC wallet worked fine the day before the update.

I've tried using a different USB cable, different USB ports, restarting my PC, making sure ledger live has not run.

Has anyone else experienced this issue?

**Comment by leejw51crypto** [comment]
hello, could you try this version?
https://github.com/crypto-com/chain-desktop-wallet/releases/tag/v0.6.9
